#!/usr/bin/env bash
set -euo pipefail

export PATH="/opt/homebrew/opt/postgresql@15/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
export AI_OS_RUNTIME_ROOT="${AI_OS_RUNTIME_ROOT:-/Users/devarshthakkar/AI_OS_ACTIVE_RECOVERY_20260710/ai-investment-os/_ai_os_runtime}"
export AI_OS_VAULT_ROOT="${AI_OS_VAULT_ROOT:-/Volumes/Devarsh SSD/Obsidian memory }"
export AI_OS_DATA_ROOT="${AI_OS_DATA_ROOT:-/Volumes/Devarsh SSD/AI OS Data}"
export AI_OS_PSQL_BIN="${AI_OS_PSQL_BIN:-/opt/homebrew/opt/postgresql@15/bin/psql}"
export AI_OS_DOCKER_BIN="${AI_OS_DOCKER_BIN:-/opt/homebrew/bin/docker}"
export AI_OS_ARTIFACT_ROOT="${AI_OS_ARTIFACT_ROOT:-/Volumes/Devarsh SSD/AI OS Data/artifacts}"
export AI_OS_PDF_PYTHON="${AI_OS_PDF_PYTHON:-/Users/devarshthakkar/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/bin/python3}"

runtime_env="${AI_OS_RUNTIME_ROOT}/.env"
if [[ -f "${runtime_env}" ]]; then
  env_value() {
    sed -n "s/^${1}=//p" "${runtime_env}" | tail -n 1
  }
  # Read only database keys; do not evaluate the general env file as shell code.
  export AI_OS_POSTGRES_HOST="${AI_OS_POSTGRES_HOST:-$(env_value AI_OS_POSTGRES_HOST)}"
  export AI_OS_POSTGRES_PORT="${AI_OS_POSTGRES_PORT:-$(env_value AI_OS_POSTGRES_PORT)}"
  export AI_OS_POSTGRES_USER="${AI_OS_POSTGRES_USER:-$(env_value AI_OS_POSTGRES_USER)}"
  export AI_OS_POSTGRES_PASSWORD="${AI_OS_POSTGRES_PASSWORD:-$(env_value AI_OS_POSTGRES_PASSWORD)}"
  export AI_OS_POSTGRES_DB="${AI_OS_POSTGRES_DB:-$(env_value AI_OS_POSTGRES_DB)}"
fi

export AI_OS_AGENT_DAEMON_INTERVAL="${AI_OS_AGENT_DAEMON_INTERVAL:-45}"
export AI_OS_ENABLE_SOURCE_FRESHNESS_SCHEDULER="${AI_OS_ENABLE_SOURCE_FRESHNESS_SCHEDULER:-1}"
export AI_OS_SOURCE_FRESHNESS_INTERVAL_SECONDS="${AI_OS_SOURCE_FRESHNESS_INTERVAL_SECONDS:-900}"
export AI_OS_SOURCE_FRESHNESS_LIMIT="${AI_OS_SOURCE_FRESHNESS_LIMIT:-100}"
export AI_OS_SOURCE_FRESHNESS_TIMEOUT_SECONDS="${AI_OS_SOURCE_FRESHNESS_TIMEOUT_SECONDS:-180}"
export AI_OS_ENABLE_OHLCV_AGGREGATION="${AI_OS_ENABLE_OHLCV_AGGREGATION:-1}"
export AI_OS_OHLCV_AGGREGATION_INTERVAL_SECONDS="${AI_OS_OHLCV_AGGREGATION_INTERVAL_SECONDS:-300}"
export AI_OS_OHLCV_AGGREGATION_TIMEOUT_SECONDS="${AI_OS_OHLCV_AGGREGATION_TIMEOUT_SECONDS:-120}"
export AI_OS_ENABLE_STRATEGY_DISCOVERY_SCHEDULER="${AI_OS_ENABLE_STRATEGY_DISCOVERY_SCHEDULER:-1}"
export AI_OS_STRATEGY_DISCOVERY_SCHEDULER_INTERVAL_SECONDS="${AI_OS_STRATEGY_DISCOVERY_SCHEDULER_INTERVAL_SECONDS:-3600}"
export AI_OS_STRATEGY_DISCOVERY_SCHEDULER_TIMEOUT_SECONDS="${AI_OS_STRATEGY_DISCOVERY_SCHEDULER_TIMEOUT_SECONDS:-900}"
export AI_OS_STRATEGY_DISCOVERY_NEWS_FEED_LIMIT="${AI_OS_STRATEGY_DISCOVERY_NEWS_FEED_LIMIT:-12}"
export AI_OS_STRATEGY_DISCOVERY_ENABLE_FILINGS="${AI_OS_STRATEGY_DISCOVERY_ENABLE_FILINGS:-1}"
export AI_OS_STRATEGY_DISCOVERY_ENABLE_FILING_EXTRACTION="${AI_OS_STRATEGY_DISCOVERY_ENABLE_FILING_EXTRACTION:-1}"
export AI_OS_STRATEGY_DISCOVERY_FILING_LOOKBACK_DAYS="${AI_OS_STRATEGY_DISCOVERY_FILING_LOOKBACK_DAYS:-2}"
export AI_OS_STRATEGY_DISCOVERY_FILING_LIMIT="${AI_OS_STRATEGY_DISCOVERY_FILING_LIMIT:-250}"
export AI_OS_STRATEGY_DISCOVERY_FILING_TIMEOUT_SECONDS="${AI_OS_STRATEGY_DISCOVERY_FILING_TIMEOUT_SECONDS:-300}"
export AI_OS_STRATEGY_DISCOVERY_FILING_EXTRACTION_LIMIT="${AI_OS_STRATEGY_DISCOVERY_FILING_EXTRACTION_LIMIT:-4}"
export AI_OS_STRATEGY_DISCOVERY_FILING_EXTRACTION_TIMEOUT_SECONDS="${AI_OS_STRATEGY_DISCOVERY_FILING_EXTRACTION_TIMEOUT_SECONDS:-300}"
export AI_OS_ENABLE_MARKET_NEWS_SCHEDULER="${AI_OS_ENABLE_MARKET_NEWS_SCHEDULER:-1}"
export AI_OS_MARKET_NEWS_INTERVAL_SECONDS="${AI_OS_MARKET_NEWS_INTERVAL_SECONDS:-900}"
export AI_OS_MARKET_NEWS_TIMEOUT_SECONDS="${AI_OS_MARKET_NEWS_TIMEOUT_SECONDS:-240}"
export AI_OS_ENABLE_MARKET_CALENDAR_SCHEDULER="${AI_OS_ENABLE_MARKET_CALENDAR_SCHEDULER:-1}"
export AI_OS_MARKET_CALENDAR_INTERVAL_SECONDS="${AI_OS_MARKET_CALENDAR_INTERVAL_SECONDS:-21600}"
export AI_OS_MARKET_CALENDAR_TIMEOUT_SECONDS="${AI_OS_MARKET_CALENDAR_TIMEOUT_SECONDS:-180}"
export AI_OS_MARKET_CALENDAR_LOOKAHEAD_DAYS="${AI_OS_MARKET_CALENDAR_LOOKAHEAD_DAYS:-45}"
export AI_OS_ENABLE_RESEARCH_HUB_REFRESH="${AI_OS_ENABLE_RESEARCH_HUB_REFRESH:-1}"
export AI_OS_RESEARCH_HUB_REFRESH_INTERVAL_SECONDS="${AI_OS_RESEARCH_HUB_REFRESH_INTERVAL_SECONDS:-1800}"
export AI_OS_RESEARCH_HUB_REFRESH_TIMEOUT_SECONDS="${AI_OS_RESEARCH_HUB_REFRESH_TIMEOUT_SECONDS:-600}"
export AI_OS_ENABLE_RESEARCH_HUB_VECTOR_REFRESH="${AI_OS_ENABLE_RESEARCH_HUB_VECTOR_REFRESH:-1}"
export AI_OS_RESEARCH_HUB_VECTOR_TIMEOUT_SECONDS="${AI_OS_RESEARCH_HUB_VECTOR_TIMEOUT_SECONDS:-1800}"

cd "/Users/devarshthakkar/Library/Application Support/AIOS/service"
exec python3 -u scripts/run_agent_message_daemon.py \
  --interval "${AI_OS_AGENT_DAEMON_INTERVAL}" \
  --source-freshness-interval "${AI_OS_SOURCE_FRESHNESS_INTERVAL_SECONDS}" \
  --source-freshness-limit "${AI_OS_SOURCE_FRESHNESS_LIMIT}" \
  --source-freshness-timeout "${AI_OS_SOURCE_FRESHNESS_TIMEOUT_SECONDS}" \
  --ohlcv-aggregation-interval "${AI_OS_OHLCV_AGGREGATION_INTERVAL_SECONDS}" \
  --ohlcv-aggregation-timeout "${AI_OS_OHLCV_AGGREGATION_TIMEOUT_SECONDS}" \
  --strategy-discovery-scheduler-interval "${AI_OS_STRATEGY_DISCOVERY_SCHEDULER_INTERVAL_SECONDS}" \
  --strategy-discovery-scheduler-timeout "${AI_OS_STRATEGY_DISCOVERY_SCHEDULER_TIMEOUT_SECONDS}" \
  --market-news-interval "${AI_OS_MARKET_NEWS_INTERVAL_SECONDS}" \
  --market-news-timeout "${AI_OS_MARKET_NEWS_TIMEOUT_SECONDS}" \
  --market-calendar-interval "${AI_OS_MARKET_CALENDAR_INTERVAL_SECONDS}" \
  --market-calendar-timeout "${AI_OS_MARKET_CALENDAR_TIMEOUT_SECONDS}" \
  --research-hub-refresh-interval "${AI_OS_RESEARCH_HUB_REFRESH_INTERVAL_SECONDS}" \
  --research-hub-refresh-timeout "${AI_OS_RESEARCH_HUB_REFRESH_TIMEOUT_SECONDS}" \
  --message-limit 10 \
  --worker-limit 5
