#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


RUNTIME_ROOT = Path(__file__).resolve().parents[1]
VAULT_ROOT = RUNTIME_ROOT.parent
MEMO_DIR = VAULT_ROOT / "ai memory" / "02 Portfolio" / "Long-Term Committee Reviews"


def sql_literal(value: object) -> str:
    if value is None:
        return "NULL"
    return "'" + str(value).replace("\x00", "").replace("'", "''") + "'"


def sql_jsonb(value: object) -> str:
    return f"{sql_literal(json.dumps(value if value is not None else {}, sort_keys=True, default=str))}::jsonb"


def run_psql_json(sql: str) -> list[dict[str, Any]]:
    command = [
        "docker",
        "exec",
        "-i",
        "ai_os_postgres",
        "psql",
        "-q",
        "-t",
        "-A",
        "-v",
        "ON_ERROR_STOP=1",
        "-U",
        "ai_os",
        "-d",
        "ai_os",
    ]
    completed = subprocess.run(command, input=sql, text=True, capture_output=True, check=False)
    if completed.returncode != 0:
        raise RuntimeError((completed.stderr or completed.stdout).strip())
    return json.loads(completed.stdout.strip() or "[]")


def clean(value: object, fallback: str = "n/a") -> str:
    if value is None:
        return fallback
    text = re.sub(r"\s+", " ", str(value).replace("\x00", " ")).strip()
    return text or fallback


def safe_slug(value: str) -> str:
    slug = re.sub(r"[^A-Za-z0-9]+", "-", value.strip()).strip("-").lower()
    return slug[:90] or "long-term-committee"


def compact_inr(value: object) -> str:
    try:
        amount = float(value or 0)
    except (TypeError, ValueError):
        amount = 0.0
    return f"INR {amount:,.0f}"


def as_list(value: object) -> list[Any]:
    return value if isinstance(value, list) else []


def as_dict(value: object) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}


def fetch_review(review_id: int) -> dict[str, Any]:
    rows = run_psql_json(
        f"""
        SELECT coalesce(json_agg(row_to_json(rows)), '[]'::json)::text
        FROM (
            SELECT *
            FROM portfolio.v_long_term_committee_queue
            WHERE id = {review_id}
        ) rows
        """
    )
    if not rows:
        raise ValueError(f"long-term committee review {review_id} not found")
    return rows[0]


def fetch_related(review: dict[str, Any]) -> dict[str, list[dict[str, Any]]]:
    thesis_id = int(review["holding_thesis_id"])
    checklists = run_psql_json(
        f"""
        SELECT coalesce(json_agg(row_to_json(rows)), '[]'::json)::text
        FROM (
            SELECT checklist_key, checklist_name, status, score, findings, evidence, owner_agent, updated_at
            FROM portfolio.v_long_term_thesis_checklists
            WHERE holding_thesis_id = {thesis_id}
            ORDER BY checklist_key
        ) rows
        """
    )
    valuations = run_psql_json(
        f"""
        SELECT coalesce(json_agg(row_to_json(rows)), '[]'::json)::text
        FROM (
            SELECT model_key, model_name, model_type, status, fair_value_low, fair_value_base,
                   fair_value_high, expected_cagr_pct, assumptions, outputs, note_path,
                   owner_agent, updated_at
            FROM portfolio.v_long_term_valuation_models
            WHERE holding_thesis_id = {thesis_id}
            ORDER BY model_key
        ) rows
        """
    )
    updates = run_psql_json(
        f"""
        SELECT coalesce(json_agg(row_to_json(rows)), '[]'::json)::text
        FROM (
            SELECT id, update_kind, checklist_key, model_key, status, findings,
                   evidence, source_summary, note_path, created_by, created_at
            FROM portfolio.v_long_term_research_updates
            WHERE holding_thesis_id = {thesis_id}
            ORDER BY created_at DESC
            LIMIT 12
        ) rows
        """
    )
    return {"checklists": checklists, "valuations": valuations, "updates": updates}


def build_memo(review: dict[str, Any], related: dict[str, list[dict[str, Any]]], actor: str) -> str:
    symbol = clean(review.get("symbol")).upper()
    source_gaps = as_list(review.get("source_gaps"))
    evidence_summary = as_dict(review.get("evidence_summary"))
    members = as_list(review.get("committee_members"))
    followups = as_list(review.get("required_followups"))
    lines = [
        f"# Long-Term Investment Committee Memo - {symbol}",
        "",
        f"Generated: {datetime.now(timezone.utc).isoformat()}",
        f"Generated by: {actor}",
        f"Review id: `{review.get('id')}`",
        f"Review key: `{review.get('review_key')}`",
        f"Thesis id: `{review.get('holding_thesis_id')}`",
        f"Exchange: `{clean(review.get('exchange'))}`",
        "",
        "## Decision Frame",
        "",
        f"- Recommended decision: `{clean(review.get('recommended_decision'))}`",
        f"- Review status: `{clean(review.get('review_status'))}`",
        f"- Approval status: `{clean(review.get('approval_status'))}`",
        f"- Capital action allowed: `{review.get('capital_action_allowed')}`",
        f"- Live execution allowed: `{review.get('live_execution_allowed')}`",
        "",
        "This memo can decide research, monitor, watchlist, hold, or reject state only. It does not authorize buy, add, trim, sell, hedge, broker order, or live strategy action.",
        "",
        "## Exposure",
        "",
        f"- Long-term gross exposure: {compact_inr(review.get('long_term_gross_exposure'))}",
        f"- Clients: {', '.join(review.get('clients') or []) or 'n/a'}",
        f"- Client count: `{review.get('client_count')}`",
        "",
        "## Evidence Summary",
        "",
        f"- Checklists complete: `{evidence_summary.get('checklist_complete_count', 0)}/{evidence_summary.get('checklist_count', 0)}`",
        f"- Valuation models complete: `{evidence_summary.get('valuation_complete_count', 0)}/{evidence_summary.get('valuation_model_count', 0)}`",
        f"- Research packets: `{evidence_summary.get('research_packet_count', 0)}`",
        f"- Latest research packet: `{clean(evidence_summary.get('latest_research_packet'))}`",
        f"- Latest packet sources: `{json.dumps(evidence_summary.get('latest_packet_sources') or {}, sort_keys=True)}`",
        "",
        "## Committee Members",
        "",
    ]
    lines.extend([f"- {clean(member)}" for member in members] or ["- No committee members recorded."])
    lines.extend(["", "## Source Gaps", ""])
    lines.extend([f"- `{clean(gap.get('gap') if isinstance(gap, dict) else gap)}`: `{json.dumps(gap, sort_keys=True)}`" for gap in source_gaps] or ["- No source gaps recorded."])
    lines.extend(["", "## Checklist Rows", ""])
    for row in related["checklists"]:
        findings = as_list(row.get("findings"))
        lines.append(f"- `{clean(row.get('checklist_key'))}` {clean(row.get('checklist_name'))}: `{clean(row.get('status'))}` owner `{clean(row.get('owner_agent'))}` score `{clean(row.get('score'))}`")
        for finding in findings[:2]:
            lines.append(f"  - Finding: {clean(finding.get('finding') if isinstance(finding, dict) else finding)}")
    if not related["checklists"]:
        lines.append("- No checklist rows found.")
    lines.extend(["", "## Valuation Modules", ""])
    for row in related["valuations"]:
        lines.append(
            f"- `{clean(row.get('model_key'))}` {clean(row.get('model_name'))}: `{clean(row.get('status'))}` "
            f"base `{clean(row.get('fair_value_base'))}`, CAGR `{clean(row.get('expected_cagr_pct'))}`"
        )
        outputs = as_dict(row.get("outputs"))
        if outputs:
            lines.append(f"  - Outputs: `{json.dumps(outputs, sort_keys=True)}`")
    if not related["valuations"]:
        lines.append("- No valuation rows found.")
    lines.extend(["", "## Recent Research Updates", ""])
    for row in related["updates"]:
        lines.append(
            f"- `{row.get('id')}` {clean(row.get('update_kind'))}: `{clean(row.get('status'))}` "
            f"{clean(row.get('checklist_key') or row.get('model_key') or row.get('note_path'))}"
        )
    if not related["updates"]:
        lines.append("- No research update ledger rows found.")
    lines.extend(["", "## Required Follow-Ups", ""])
    for item in followups:
        if isinstance(item, dict):
            lines.append(f"- {clean(item.get('owner_agent'))}: {clean(item.get('action'))}")
        else:
            lines.append(f"- {clean(item)}")
    if not followups:
        lines.append("- None recorded.")
    lines.extend(
        [
            "",
            "## Charlie Chair Notes",
            "",
            "- If source gaps exist, the only acceptable decision is `research_more` or `reject`.",
            "- `approve_hold` is allowed only when the thesis is already owned and evidence is complete enough for a hold decision.",
            "- `approve_watchlist` is not a buy order. It only moves the idea to an approved watchlist state.",
            "- Any capital action requires a separate future approval workflow with Risk Office and human approval.",
        ]
    )
    return "\n".join(lines) + "\n"


def insert_obsidian_note(note_path: Path, title: str, summary: str) -> None:
    rel_path = str(note_path.relative_to(VAULT_ROOT))
    run_psql_json(
        f"""
        WITH upserted AS (
            INSERT INTO knowledge.obsidian_notes (
                vault_path, note_path, title, note_type, tags, frontmatter,
                content_hash, body_summary, last_modified_at, indexed_at
            )
            VALUES (
                {sql_literal(str(VAULT_ROOT))},
                {sql_literal(rel_path)},
                {sql_literal(title)},
                'long_term_committee_memo',
                ARRAY['ai-os','long-term','committee']::text[],
                {sql_jsonb({'source': 'generate_long_term_committee_memo.py'})},
                md5({sql_literal(note_path.read_text())}),
                {sql_literal(summary)},
                now(),
                now()
            )
            ON CONFLICT (note_path) DO UPDATE SET
                title = EXCLUDED.title,
                note_type = EXCLUDED.note_type,
                tags = EXCLUDED.tags,
                frontmatter = EXCLUDED.frontmatter,
                content_hash = EXCLUDED.content_hash,
                body_summary = EXCLUDED.body_summary,
                last_modified_at = EXCLUDED.last_modified_at,
                indexed_at = now()
            RETURNING *
        )
        SELECT coalesce(json_agg(row_to_json(upserted)), '[]'::json)::text FROM upserted
        """
    )


def update_review(review_id: int, rel_path: str, actor: str) -> dict[str, Any]:
    rows = run_psql_json(
        f"""
        WITH updated AS (
            UPDATE portfolio.long_term_committee_reviews
            SET memo_note_path = {sql_literal(rel_path)},
                memo_status = 'generated',
                memo_generated_at = now(),
                updated_at = now()
            WHERE id = {review_id}
            RETURNING id, holding_thesis_id, memo_note_path, memo_status, memo_generated_at, approval_id, task_id
        ),
        inbox AS (
            INSERT INTO agent.inbox_items (
                task_id, title, owner_agent, status, priority, recommended_action,
                evidence, target_workspace
            )
            SELECT
                task_id,
                'Review Long-Term committee memo: ' || {sql_literal(rel_path)},
                'Charlie Munger',
                'needs_review',
                'high',
                'Resolve the Long-Term committee decision. No capital action or live execution is authorized by this memo.',
                jsonb_build_array(jsonb_build_object('long_term_committee_review_id', id), jsonb_build_object('memo_note_path', {sql_literal(rel_path)})),
                'Long-Term Office'
            FROM updated
            RETURNING id
        )
        SELECT coalesce(json_agg(row_to_json(rows)), '[]'::json)::text
        FROM (
            SELECT updated.*, (SELECT id FROM inbox LIMIT 1) AS inbox_id, {sql_literal(actor)} AS generated_by
            FROM updated
        ) rows
        """
    )
    return rows[0] if rows else {}


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate a Long-Term Investment Committee memo into Obsidian.")
    parser.add_argument("--review-id", type=int, required=True)
    parser.add_argument("--actor", default="Long-Term Portfolio Manager")
    args = parser.parse_args()
    try:
        review = fetch_review(args.review_id)
        related = fetch_related(review)
        MEMO_DIR.mkdir(parents=True, exist_ok=True)
        symbol = clean(review.get("symbol")).upper()
        stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        note_path = MEMO_DIR / f"{stamp}-{safe_slug(symbol)}-committee-memo.md"
        note_path.write_text(build_memo(review, related, args.actor))
        rel_path = str(note_path.relative_to(VAULT_ROOT))
        insert_obsidian_note(note_path, f"Long-Term Investment Committee Memo - {symbol}", f"Long-Term committee memo for {symbol}; review id {args.review_id}.")
        result = update_review(args.review_id, rel_path, args.actor)
    except Exception as exc:
        print(str(exc), file=sys.stderr)
        return 1
    print(json.dumps({"review_id": args.review_id, "note_path": rel_path, "database": result}, indent=2, sort_keys=True, default=str))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
