#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import mimetypes
import re
import subprocess
import sys
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


RUNTIME_ROOT = Path(__file__).resolve().parents[1]
VAULT_ROOT = RUNTIME_ROOT.parent
NOTE_DIR = VAULT_ROOT / "ai memory" / "05 Filings and Transcripts" / "Long-Term Source Documents"
USER_AGENT = "AI-OS-Research/0.1 (source provenance; contact local user)"


def sql_literal(value: object) -> str:
    if value is None:
        return "NULL"
    return "'" + str(value).replace("\x00", "").replace("'", "''") + "'"


def sql_int(value: object) -> str:
    if value in (None, ""):
        return "NULL"
    return str(int(value))


def sql_jsonb(value: object) -> str:
    return f"{sql_literal(json.dumps(value if value is not None else {}, sort_keys=True, default=str))}::jsonb"


def run_psql_json(sql: str) -> list[dict[str, Any]]:
    command = [
        "docker",
        "exec",
        "-i",
        "ai_os_postgres",
        "psql",
        "-q",
        "-t",
        "-A",
        "-v",
        "ON_ERROR_STOP=1",
        "-U",
        "ai_os",
        "-d",
        "ai_os",
    ]
    completed = subprocess.run(command, input=sql, text=True, capture_output=True, check=False)
    if completed.returncode != 0:
        raise RuntimeError((completed.stderr or completed.stdout).strip())
    return json.loads(completed.stdout.strip() or "[]")


def clean(value: object, fallback: str = "n/a") -> str:
    if value is None:
        return fallback
    text = re.sub(r"\s+", " ", str(value).replace("\x00", " ")).strip()
    return text or fallback


def safe_slug(value: str) -> str:
    slug = re.sub(r"[^A-Za-z0-9]+", "-", value.strip()).strip("-").lower()
    return slug[:90] or "source-document"


def content_hash(*values: object) -> str:
    digest = hashlib.sha256()
    for value in values:
        digest.update(str(value or "").encode("utf-8", errors="ignore"))
        digest.update(b"\x1f")
    return digest.hexdigest()


def verify_url(source_url: str) -> dict[str, Any]:
    request = urllib.request.Request(source_url, method="HEAD", headers={"User-Agent": USER_AGENT})
    try:
        with urllib.request.urlopen(request, timeout=20) as response:
            return {
                "http_status": response.status,
                "content_type": response.headers.get("Content-Type"),
                "content_length": response.headers.get("Content-Length"),
                "verified": 200 <= response.status < 400,
                "method": "HEAD",
            }
    except Exception as head_error:
        get_request = urllib.request.Request(source_url, headers={"User-Agent": USER_AGENT})
        try:
            with urllib.request.urlopen(get_request, timeout=25) as response:
                response.read(2048)
                return {
                    "http_status": response.status,
                    "content_type": response.headers.get("Content-Type"),
                    "content_length": response.headers.get("Content-Length"),
                    "verified": 200 <= response.status < 400,
                    "method": "GET",
                    "head_error": f"{type(head_error).__name__}: {head_error}",
                }
        except Exception as get_error:
            return {
                "http_status": None,
                "content_type": None,
                "content_length": None,
                "verified": False,
                "method": "HEAD/GET",
                "error": f"{type(get_error).__name__}: {get_error}",
                "head_error": f"{type(head_error).__name__}: {head_error}",
            }


def fetch_request(source_request_id: int) -> dict[str, Any]:
    rows = run_psql_json(
        f"""
        SELECT coalesce(json_agg(row_to_json(rows)), '[]'::json)::text
        FROM (
            SELECT *
            FROM portfolio.v_long_term_source_requests
            WHERE id = {int(source_request_id)}
            LIMIT 1
        ) rows
        """
    )
    if not rows:
        raise ValueError(f"Long-Term source request {source_request_id} not found")
    return rows[0]


def build_note(request: dict[str, Any], args: argparse.Namespace, verification: dict[str, Any], artifact_id: int | None) -> str:
    symbol = clean(request.get("symbol")).upper()
    lines = [
        f"# Source Document - {symbol} - {args.document_type}",
        "",
        f"Generated: {datetime.now(timezone.utc).isoformat()}",
        f"Generated by: {args.actor}",
        f"Symbol: `{symbol}`",
        f"Company: `{clean(request.get('company_name'))}`",
        f"Source request: `{request.get('request_key')}`",
        f"Required module: `{clean(request.get('required_for_module'))}`",
        f"Required by: `{clean(request.get('required_by_agent'))}`",
        "",
        "## Source",
        "",
        f"- Title: {args.title}",
        f"- Source URL: {args.source_url}",
        f"- Local path: {clean(args.local_path)}",
        f"- Document type: `{args.document_type}`",
        f"- HTTP status: `{clean(verification.get('http_status'))}`",
        f"- Content type: `{clean(verification.get('content_type'))}`",
        f"- Raw artifact id: `{clean(artifact_id)}`",
        "",
        "## Guardrail",
        "",
        "This note only registers source evidence. It does not authorize buy, sell, trim, add, hedge, broker order, or live strategy action.",
        "",
        "## Provenance",
        "",
        "- `source_url` is stored in frontmatter and raw artifact metadata.",
        "- The satisfaction checker must still verify this source against the request.",
        "- The specialist module should be rerun only after the request is marked satisfied.",
    ]
    if args.summary:
        lines.extend(["", "## Summary", "", args.summary])
    return "\n".join(lines) + "\n"


def insert_raw_artifact(request: dict[str, Any], args: argparse.Namespace, verification: dict[str, Any]) -> int:
    symbol = clean(request.get("symbol")).upper()
    mime_type = verification.get("content_type") or mimetypes.guess_type(args.source_url)[0] or "application/octet-stream"
    hash_value = content_hash(symbol, args.document_type, args.title, args.source_url, args.local_path)
    metadata = {
        "symbol": symbol,
        "exchange": request.get("exchange"),
        "company_name": request.get("company_name"),
        "document_type": args.document_type,
        "source_request_id": request.get("id"),
        "request_key": request.get("request_key"),
        "required_for_module": request.get("required_for_module"),
        "required_by_agent": request.get("required_by_agent"),
        "source_url": args.source_url,
        "verification": verification,
        "registered_by": args.actor,
    }
    rows = run_psql_json(
        f"""
        WITH rows AS (
            INSERT INTO core.raw_artifacts (
                source_system_id, artifact_type, title, source_url, local_path,
                content_hash, mime_type, sensitivity, metadata
            )
            VALUES (
                NULL,
                'long_term_source_document',
                {sql_literal(args.title)},
                {sql_literal(args.source_url)},
                {sql_literal(args.local_path)},
                {sql_literal(hash_value)},
                {sql_literal(mime_type)},
                'public',
                {sql_jsonb(metadata)}
            )
            ON CONFLICT (source_system_id, source_url, local_path, content_hash) DO UPDATE SET
                title = EXCLUDED.title,
                mime_type = EXCLUDED.mime_type,
                sensitivity = EXCLUDED.sensitivity,
                metadata = EXCLUDED.metadata,
                captured_at = now()
            RETURNING id
        )
        SELECT coalesce(json_agg(row_to_json(rows)), '[]'::json)::text FROM rows
        """
    )
    if not rows:
        raise ValueError("raw artifact registration returned no id")
    return int(rows[0]["id"])


def insert_obsidian_note(note_path: Path, request: dict[str, Any], args: argparse.Namespace, verification: dict[str, Any], artifact_id: int) -> int:
    rel_path = str(note_path.relative_to(VAULT_ROOT))
    frontmatter = {
        "source": "register_long_term_source_document.py",
        "source_url": args.source_url,
        "local_path": args.local_path,
        "document_type": args.document_type,
        "source_request_id": request.get("id"),
        "request_key": request.get("request_key"),
        "raw_artifact_id": artifact_id,
        "http_status": verification.get("http_status"),
    }
    tags = ["ai-os", "long-term", "source-document", safe_slug(args.document_type)]
    rows = run_psql_json(
        f"""
        WITH rows AS (
            INSERT INTO knowledge.obsidian_notes (
                vault_path, note_path, title, note_type, tags, frontmatter,
                content_hash, body_summary, last_modified_at, indexed_at
            )
            VALUES (
                {sql_literal(str(VAULT_ROOT))},
                {sql_literal(rel_path)},
                {sql_literal(f"Source Document - {clean(request.get('symbol')).upper()} - {args.document_type}")},
                'long_term_source_document',
                ARRAY[{','.join(sql_literal(tag) for tag in tags)}]::text[],
                {sql_jsonb(frontmatter)},
                md5({sql_literal(note_path.read_text())}),
                {sql_literal(f"{args.document_type} source for {clean(request.get('symbol')).upper()}: {args.source_url}")},
                now(),
                now()
            )
            ON CONFLICT (note_path) DO UPDATE SET
                title = EXCLUDED.title,
                note_type = EXCLUDED.note_type,
                tags = EXCLUDED.tags,
                frontmatter = EXCLUDED.frontmatter,
                content_hash = EXCLUDED.content_hash,
                body_summary = EXCLUDED.body_summary,
                last_modified_at = EXCLUDED.last_modified_at,
                indexed_at = now()
            RETURNING id
        )
        SELECT coalesce(json_agg(row_to_json(rows)), '[]'::json)::text FROM rows
        """
    )
    if not rows:
        raise ValueError("Obsidian source note registration returned no id")
    return int(rows[0]["id"])


def register_document(args: argparse.Namespace) -> dict[str, Any]:
    request = fetch_request(args.source_request_id)
    verification = verify_url(args.source_url)
    artifact_id = insert_raw_artifact(request, args, verification)
    symbol = clean(request.get("symbol")).upper()
    NOTE_DIR.mkdir(parents=True, exist_ok=True)
    source_digest = content_hash(args.source_url)[:12]
    note_path = NOTE_DIR / f"request-{request['id']}-{safe_slug(symbol)}-{safe_slug(args.document_type)}-{source_digest}.md"
    note_path.write_text(build_note(request, args, verification, artifact_id))
    note_id = insert_obsidian_note(note_path, request, args, verification, artifact_id)
    rel_path = str(note_path.relative_to(VAULT_ROOT))
    document_key = f"lt-doc-{request['id']}-{safe_slug(args.document_type)}-{content_hash(args.source_url)[:12]}"
    evidence = [
        {"table": "portfolio.long_term_source_requests", "id": request.get("id")},
        {"table": "core.raw_artifacts", "id": artifact_id},
        {"table": "knowledge.obsidian_notes", "id": note_id},
        {"source_url": args.source_url},
        {"capital_action_allowed": False},
        {"live_execution_allowed": False},
    ]
    rows = run_psql_json(
        f"""
        WITH rows AS (
            INSERT INTO portfolio.long_term_source_documents (
                document_key, source_request_id, holding_thesis_id,
                specialist_output_id, assignment_id, symbol, exchange, company_name,
                document_type, document_title, source_url, local_path, source_name,
                provenance_status, http_status, raw_artifact_id, obsidian_note_id,
                note_path, evidence, metadata, created_by, updated_at
            )
            VALUES (
                {sql_literal(document_key)},
                {int(request['id'])},
                {int(request['holding_thesis_id'])},
                {sql_int(request.get('specialist_output_id'))},
                {sql_int(request.get('assignment_id'))},
                {sql_literal(symbol)},
                {sql_literal(request.get('exchange'))},
                {sql_literal(request.get('company_name'))},
                {sql_literal(args.document_type)},
                {sql_literal(args.title)},
                {sql_literal(args.source_url)},
                {sql_literal(args.local_path)},
                {sql_literal(args.source_name)},
                {sql_literal('verified' if verification.get('verified') else 'registered_unverified')},
                {sql_int(verification.get('http_status'))},
                {artifact_id},
                {note_id},
                {sql_literal(rel_path)},
                {sql_jsonb(evidence)},
                {sql_jsonb({'verification': verification, 'summary': args.summary})},
                {sql_literal(args.actor)},
                now()
            )
            ON CONFLICT (source_request_id, source_url) DO UPDATE SET
                document_type = EXCLUDED.document_type,
                document_title = EXCLUDED.document_title,
                local_path = EXCLUDED.local_path,
                source_name = EXCLUDED.source_name,
                provenance_status = EXCLUDED.provenance_status,
                http_status = EXCLUDED.http_status,
                raw_artifact_id = EXCLUDED.raw_artifact_id,
                obsidian_note_id = EXCLUDED.obsidian_note_id,
                note_path = EXCLUDED.note_path,
                evidence = EXCLUDED.evidence,
                metadata = EXCLUDED.metadata,
                updated_at = now()
            RETURNING *
        )
        SELECT coalesce(json_agg(row_to_json(rows)), '[]'::json)::text FROM rows
        """
    )
    if not rows:
        raise ValueError("source document registration returned no row")
    doc = rows[0]
    return {
        "source_document_id": doc["id"],
        "source_request_id": request["id"],
        "request_key": request["request_key"],
        "symbol": symbol,
        "document_type": args.document_type,
        "source_url": args.source_url,
        "http_status": verification.get("http_status"),
        "provenance_status": doc["provenance_status"],
        "raw_artifact_id": artifact_id,
        "obsidian_note_id": note_id,
        "note_path": rel_path,
        "capital_action_allowed": False,
        "live_execution_allowed": False,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Register an official Long-Term source document.")
    parser.add_argument("--source-request-id", type=int, required=True)
    parser.add_argument("--title", required=True)
    parser.add_argument("--source-url", required=True)
    parser.add_argument("--document-type", default="annual_report")
    parser.add_argument("--source-name", default="official_company_source")
    parser.add_argument("--local-path")
    parser.add_argument("--summary")
    parser.add_argument("--actor", default="Filings and Transcript Analyst")
    args = parser.parse_args()
    try:
        result = register_document(args)
    except Exception as exc:
        print(str(exc), file=sys.stderr)
        return 1
    print(json.dumps(result, indent=2, sort_keys=True, default=str))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
