import React from "react";
import { useSearchParams } from "react-router-dom";
import { AlertTriangle, ArrowRight, BookOpen, CheckCircle2, Clock3, ExternalLink, FileCheck2, FileText, History, Play, Radio, RefreshCw, Search, ShieldCheck, Sparkles, UsersRound } from "lucide-react";
import { useResearchCases, useResearchUpdates } from "../../data/queries";
import { API_BASE_URL } from "../../data/client";
import { useApproveResearchModelPreflight, usePrepareResearchCaseResume, useRepairResearchCase, useRepairResearchCaseReportDelivery, useStartResearchCase } from "../../data/actions";
import { num, text, formatRelative } from "../../data/liveRow";
import type { LiveRow } from "../../data/liveRow";
import { Badge, Button, Empty, Skeleton, StatusPill } from "../../system/primitives";
import { useUIStore } from "../../store";
import { ResearchCasesCss } from "./ResearchCases.css";
import { ResearchDeskCss } from "./ResearchDesk.css";
import { ResearchDeskNav } from "./ResearchDeskNav";

const ROLE_LABELS: Record<string, string> = {
  company_business: "Business and segments", filings: "Official filings", financials: "Financial history & ratios",
  management: "Management and allocation", industry_moat: "Industry, TAM, value chain & moat", valuation: "Valuation & scenarios",
  bear_risk: "Catalysts, bear case & risks", lead_synthesis: "Lead analyst synthesis",
  executive_summary: "Executive investment summary", independent_review: "Independent challenge",
  committee_review: "Investment committee brief",
};
const STAGES = [
  ["sources","Sources"],["extract","Extraction"],["specialists","Analysis"],["synthesis","Synthesis"],["review","Independent review"],["report","Pack & decision"],
] as const;
function percent(done:number,total:number){return total>0?Math.round(done/total*100):0;}
function arrLen(row:LiveRow,key:string){return Array.isArray(row[key])?row[key].length:0;}
function caseStage(row:LiveRow){const status=text(row,"status");if(num(row,"agent_blocked")>0||num(row,"source_job_blocked")>0||num(row,"high_blocker_count")>0)return "blocked";if(status==="active"&&Math.max(num(row,"source_count"),num(row,"preflight_source_count"))===0&&num(row,"model_run_count")===0)return "awaiting_sources";return status;}
function statusTone(status:string):"ok"|"warn"|"risk"|"accent"|"default"{if(["completed","done","accepted","reviewed"].includes(status))return "ok";if(["blocked","failed"].includes(status))return "risk";if(["active","review","running"].includes(status))return "accent";if(["proposed","collecting","awaiting_sources","queued","retry_wait"].includes(status))return "warn";return "default";}
function rawFailure(value:unknown){if(value instanceof Error)return value.message;if(typeof value==="string")return value;try{return JSON.stringify(value);}catch{return "";}}
function redactTechnicalDetail(value:unknown){return (rawFailure(value)||"No additional diagnostic detail was returned.")
  .replace(/file:\/\/\/(?:Volumes|Users|private|var|tmp|Applications)\/[^"'\]\}\n\r;,]+/gi,"[local path hidden]")
  .replace(/\/(?:Volumes|Users|private|var|tmp|Applications)\/[^"'\]\}\n\r;,]+/g,"[local path hidden]")
  .replace(/\b(?:authorization\s*:\s*bearer|api[_-]?key|access[_-]?token|refresh[_-]?token|password|secret)\s*[:=]\s*[^\s,;"'}]+/gi,"[credential hidden]")
  .replace(/\bsk-[A-Za-z0-9_-]{8,}\b/g,"[credential hidden]");}
function failureCopy(value:unknown){const raw=rawFailure(value),lower=raw.toLowerCase(),technical=raw?redactTechnicalDetail(raw):"";
  if(lower.includes("pypdf")||lower.includes("pdfreader")||lower.includes("pdf extraction"))return {summary:"One or more filings could not be read.",nextAction:"Retry extraction; if it fails again, open the source and confirm that the PDF is readable.",technical};
  if((lower.includes("timeoutexpired")||lower.includes("timed out"))&&(lower.includes("chrome")||lower.includes("print-to-pdf")||lower.includes("report")))return {summary:"The research pack was saved, but PDF export timed out.",nextAction:"Retry report export; completed analysis remains available.",technical};
  if(lower.includes("postgres")||lower.includes("psycopg")||lower.includes("sqlstate")||lower.includes("relation does not exist"))return {summary:"The research record could not be refreshed.",nextAction:"Retry once, then open System Health if the problem repeats.",technical};
  if(lower.includes("unauthorized")||lower.includes("forbidden")||lower.includes("csrf")||/\b(?:401|403)\b/.test(lower))return {summary:"Your session could not authorize this action.",nextAction:"Refresh the page and retry; sign in again if the problem repeats.",technical};
  if(lower.includes("network")||lower.includes("fetch")||lower.includes("http")||lower.includes("source"))return {summary:"The public source could not be reached.",nextAction:"Check the source link, then retry the failed stage.",technical};
  return {summary:"This research step did not finish.",nextAction:"Retry the failed stage; saved research and completed work remain preserved.",technical};}
function failureToast(value:unknown){const copy=failureCopy(value);return copy.summary+" "+copy.nextAction;}
function blockerCopy(row:LiveRow){
  const detail=text(row,"detail");
  const lower=detail.toLowerCase();
  if(lower.includes("pypdf")||lower.includes("pdfreader")||lower.includes("pdf extraction")||lower.includes("timeoutexpired")||lower.includes("print-to-pdf")||lower.includes("chrome")||lower.trim().startsWith("{")||lower.includes("error_message")||lower.includes("postgres")||lower.includes("psycopg")||lower.includes("sqlstate"))return failureCopy(detail);
  return {summary:detail||"The failed stage is preserved and has an explicit repair path.",nextAction:"Review the repair scope below, then retry only the failed stage.",technical:""};
}

export default function ResearchCases(){
  const [params,setParams]=useSearchParams(); const page=Math.max(1,Number(params.get("page")||1)); const caseId=Math.max(0,Number(params.get("case_id")||0)); const status=params.get("status")||"";
  const serverStatus=status==="blocked"?"":status; const query=useResearchCases({page,status:serverStatus}); const detailQuery=useResearchCases({caseId,enabled:caseId>0}); const updates=useResearchUpdates({scope:"followed",status:"new",page:1,pageSize:20}); const updateRows=updates.data?.items??[]; const start=useStartResearchCase(); const approve=useApproveResearchModelPreflight(); const prepareResume=usePrepareResearchCaseResume(); const repair=useRepairResearchCase(); const reportRepair=useRepairResearchCaseReportDelivery();
  const setAssistantScope=useUIStore(s=>s.setAssistantScope); const queueAssistantMessage=useUIStore(s=>s.queueAssistantMessage); const pushToast=useUIStore(s=>s.pushToast); const [request,setRequest]=React.useState("");
  const listData=query.data; const data=caseId?detailQuery.data:query.data; const library=(listData?.library_summary||data?.library_summary||{}) as LiveRow; const selectedRaw=data?.cases.find(row=>num(row,"id")===(caseId||data.selected_case_id))||data?.cases[0];
  const allCases=listData?.cases||[]; const cases=status==="blocked"?allCases.filter(row=>caseStage(row)==="blocked"):allCases; const selected=status==="blocked"&&!caseId?undefined:selectedRaw; const reviewCount=cases.filter(row=>text(row,"status")==="review").length; const attentionCount=cases.filter(row=>["blocked","proposed"].includes(caseStage(row))).length;
  const followedBySymbol=new Map<string,LiveRow>(); cases.filter(row=>Boolean(row.is_followed)).forEach(row=>followedBySymbol.set(text(row,"ticker").toUpperCase(),row)); updateRows.forEach(row=>{const symbol=text(row,"symbol").toUpperCase();if(symbol&&!followedBySymbol.has(symbol))followedBySymbol.set(symbol,{...row,id:num(row,"research_case_id"),ticker:symbol});}); const followed=Array.from(followedBySymbol.values());
  const followedUpdates=updateRows.slice(0,8);
  function refetchAll(){void query.refetch();if(caseId>0)void detailQuery.refetch();void updates.refetch();}
  function launchCharlie(event:React.FormEvent){event.preventDefault();const company=request.trim();if(!company){pushToast({title:"Add a company or question",message:"Enter a company name, ticker, or investment question so Charlie can prepare the research plan.",tone:"warn",duration:4500});return;}const command=/^start\s/i.test(company)?company:`Start long-term research on ${company}`;setAssistantScope("charlie");queueAssistantMessage(command);pushToast({title:"Research request sent to Charlie",message:"Review the resolved company, source boundary and estimated cost in Charlie, then explicitly approve Start.",tone:"ok",duration:6000});setRequest("");}
  function choose(id:number){setParams(current=>{current.set("case_id",String(id));current.delete("page");return current;});}
  function approveAndStart(row:LiveRow){
    const id=num(row,"id"),preflightId=num(row,"preflight_id"),sourceCount=Math.max(num(row,"source_count"),num(row,"preflight_source_count")),rate=num(row,"exchange_rate_inr_per_usd",87),estimate=num(row,"estimated_cost_usd"),hardMax=num(row,"hard_max_cost_usd");
    if(!id){pushToast({title:"Case could not be opened",message:"Refresh the workstream list, then select the company again.",tone:"risk",duration:5500});return;}
    if(!preflightId){const company=text(row,"company_name",text(row,"ticker"));setAssistantScope("charlie");queueAssistantMessage(`Prepare a bounded long-term research plan for ${company}`);pushToast({title:"Plan request sent to Charlie",message:"Charlie will resolve the company and prepare the source and cost plan before Start becomes available.",tone:"ok",duration:6500});return;}
    const boundary=sourceCount===0?"The stack will collect official public sources first. Paid agents stay at INR 0 until a packet qualifies.":`Current qualified sources: ${sourceCount}. Estimated model cost INR ${(estimate*rate).toFixed(2)}; hard stop INR ${(hardMax*rate).toFixed(2)}.`;
    if(!window.confirm(`Start Research Case #${id} for ${text(row,"company_name")}?\n\n${boundary}\n\nThe stack will collect, extract and analyze authorized public sources automatically. Private data stays on Devarsh SSD. No broker, client or external writes.`))return;
    const doStart=()=>start.mutate({research_case_id:id,model_preflight_id:preflightId,operator_confirmed:true,actor:"Devarsh via Research Cases"},{onSuccess:(result)=>{const runtime=(result.autonomous_runtime||{}) as LiveRow;pushToast({title:`Research Case #${id} started`,message:num(runtime,"model_run_count")?`${num(runtime,"model_run_count")} specialist runs were queued. Open this case to track progress.`:"Official-source collection was queued. Open this case to track progress.",tone:"ok",duration:7000});refetchAll();},onError:error=>pushToast({title:"Research could not start",message:failureToast(error),tone:"risk",duration:7000})});
    if(text(row,"preflight_status")==="approved")doStart();else approve.mutate({preflight_id:preflightId,operator_confirmed:true,actor:"Devarsh via Research Cases"},{onSuccess:doStart,onError:error=>pushToast({title:"Approval failed",message:failureToast(error),tone:"risk",duration:7000})});
  }
  function repairCase(row:LiveRow){
    const id=num(row,"id"),preflightId=num(row,"preflight_id"),rate=num(row,"exchange_rate_inr_per_usd",87),estimate=num(row,"estimated_cost_usd"),hardMax=num(row,"hard_max_cost_usd"),preflightStatus=text(row,"preflight_status");
    const openCaseBlockers=(data?.blockers||[]).filter(blocker=>["open","retrying"].includes(text(blocker,"status")));
    const deliveryKeys=new Set(["report_pdf_render","research_pack_generation"]);
    const deliveryOnly=openCaseBlockers.length>0&&openCaseBlockers.every(blocker=>deliveryKeys.has(text(blocker,"blocker_key")));
    if(!id){pushToast({title:"Repair could not be prepared",message:"Refresh the workstream list, then select the company again.",tone:"risk",duration:5500});return;}
    if(deliveryOnly){
      if(!window.confirm("Repair report delivery for Research Case #"+id+"?\n\nThis local INR 0 repair re-renders the existing HTML report to PDF, or rebuilds delivery from stored sections and evidence if no report row exists. It creates no model preflight, source job, model run, broker action or external write."))return;
      reportRepair.mutate({research_case_id:id,operator_confirmed:true,actor:"Devarsh via Research Cases"},{onSuccess:(result)=>{pushToast({title:"Report delivery repaired for Case #"+id,message:Boolean(result.pdf_download_available)?"The same saved research pack now has an available PDF. No research stage was rerun.":"The source-backed HTML report remains available and the bounded local PDF retry is recorded. No paid research was rerun.",tone:Boolean(result.pdf_download_available)?"ok":"warn",duration:8500});refetchAll();},onError:error=>pushToast({title:"Local report repair failed",message:failureToast(error),tone:"risk",duration:9000})});
      return;
    }
    const latestCosts:Record<string,LiveRow>={};(data?.model_runs||[]).forEach(run=>{const role=text(run,"role_key"),current=latestCosts[role];if(!current||num(run,"iteration")>num(current,"iteration")||(num(run,"iteration")===num(current,"iteration")&&num(run,"attempt")>num(current,"attempt")))latestCosts[role]=run;});
    const reconciliationUsd=["lead_synthesis","executive_summary","independent_review"].reduce((sum,role)=>sum+num(latestCosts[role]||{},"actual_cost_usd"),0);
    const runRepair=(forceNewIteration:boolean)=>repair.mutate({research_case_id:id,model_preflight_id:preflightId,force_new_iteration:forceNewIteration,operator_confirmed:true,actor:"Devarsh via Research Cases"},{onSuccess:()=>{pushToast({title:"Case #"+id+" resumed",message:forceNewIteration?"A corrected public packet is running through specialists and independent review.":"The failed synthesis/review stage is retrying inside the existing approved ceiling; completed source and specialist work is preserved.",tone:"ok",duration:8000});refetchAll();},onError:error=>pushToast({title:"Resume failed",message:failureToast(error),tone:"risk",duration:9000})});
    if(preflightStatus==="approved"){if(!window.confirm("Resolve the current blocker for Research Case #"+id+"?\n\nThis retries only the failed synthesis and independent-review stages. Completed collection, extraction and specialist work is preserved. Expected reconciliation cost is about INR "+(reconciliationUsd*rate).toFixed(2)+" based on the latest three stages. It may use the remaining budget inside the already-approved hard stop of INR "+(hardMax*rate).toFixed(2)+".\n\nPublic sources only; private data stays on Devarsh SSD. No broker, client, external write or capital action."))return;runRepair(false);return;}
    if(preflightStatus!=="awaiting_approval"){prepareResume.mutate({research_case_id:id,actor:"Devarsh via Research Cases"},{onSuccess:(result)=>{const plan=(result.preflight||{}) as LiveRow;pushToast({title:"Fresh cost plan ready for Case #"+id,message:"Estimated INR "+(num(plan,"estimated_cost_usd")*num(plan,"exchange_rate_inr_per_usd",87)).toFixed(2)+"; hard stop INR "+(num(plan,"hard_max_cost_usd")*num(plan,"exchange_rate_inr_per_usd",87)).toFixed(2)+". Review it here, then explicitly approve Resume. No model was called.",tone:"ok",duration:9000});refetchAll();},onError:error=>pushToast({title:"Could not prepare resume plan",message:failureToast(error),tone:"risk",duration:8000})});return;}
    if(!window.confirm("Resume corrected Research Case #"+id+"?\n\nEstimated new iteration cost INR "+(estimate*rate).toFixed(2)+"; hard stop INR "+(hardMax*rate).toFixed(2)+".\n\nThis approves only public-source model analysis. Private data stays on Devarsh SSD. No broker, client, external write or capital action."))return;
    approve.mutate({preflight_id:preflightId,operator_confirmed:true,actor:"Devarsh via Research Cases"},{onSuccess:()=>runRepair(true),onError:error=>pushToast({title:"Cost approval failed",message:failureToast(error),tone:"risk",duration:8000})});
  }
  if(query.error||detailQuery.error){const copy=failureCopy(query.error||detailQuery.error);return <div className="aios-destination"><style>{ResearchCasesCss + ResearchDeskCss}</style><div className="rc-error"><AlertTriangle/><div><strong>Research tracker is unavailable</strong><p>{copy.summary} {copy.nextAction}</p><Button onClick={refetchAll}>Retry</Button>{copy.technical?<details><summary>Technical detail</summary><code>{copy.technical}</code></details>:null}</div></div></div>;}
  return <div className="aios-destination rc-page"><style>{ResearchCasesCss + ResearchDeskCss}</style>
    <header className="rc-hero"><div><span className="rc-eyebrow">CHARLIE RESEARCH DESK</span><h1>Company Research</h1><p>Approve once, then follow official-source collection, analysis, review and the final company pack.</p></div><form onSubmit={launchCharlie} className="rc-launch"><Search size={18}/><input value={request} onChange={e=>setRequest(e.target.value)} placeholder="Company, ticker, or investment question…" aria-label="Company, ticker, or idea" required/><button type="submit"><Sparkles size={16}/> Start with Charlie</button></form></header>
    <section className="rc-assurance"><span><ShieldCheck size={16}/> Durable in Postgres</span><span>Artifacts on Devarsh SSD</span><span>Public packets only</span><span>No broker/client writes</span><span>{num(library,"total_artifacts")} prior files · {num(library,"linked_companies")} companies linked</span></section>
    <ResearchDeskNav />
    <section className="rc-pulse" aria-label="Research desk summary"><div><span>RUNNING</span><strong>{cases.filter(row=>["active","collecting"].includes(text(row,"status"))).length}</strong><small>autonomous cases</small></div><div><span>DRAFT REVIEW</span><strong>{reviewCount}</strong><small>packs awaiting review</small></div><div className={attentionCount?"has-attention":""}><span>YOUR ACTION</span><strong>{attentionCount}</strong><small>start or repair</small></div><div><span>FOLLOWING</span><strong>{followed.length}</strong><small>companies monitored</small></div></section>
    <section className="rc-monitor"><header><div><span>FOLLOWED COMPANY PULSE</span><h2>Material changes stay attached to the company</h2><p>Only governed thesis changes and official filings for followed companies appear here. Open the company dashboard for the full history.</p></div><a href="/today">Open Today brief <ArrowRight size={14}/></a></header><div className="rc-following">{followed.map(row=><a key={num(row,"id")} href={text(row,"thesis_href")||num(row,"holding_thesis_id")?text(row,"thesis_href","/fundamental/theses?symbol="+encodeURIComponent(text(row,"ticker"))):text(row,"case_href","/research/cases?case_id="+num(row,"id"))}><Radio size={13}/><strong>{text(row,"ticker")}</strong><span>{text(row,"company_name")}</span></a>)}</div>{followedUpdates.length?<details><summary><History size={15}/> Latest sourced changes <Badge tone="accent">{followedUpdates.length}</Badge></summary><div className="rc-update-list">{followedUpdates.map((row,index)=><article key={text(row,"update_key",text(row,"source_identifier",String(index)))}><div><span>{text(row,"source_kind",text(row,"update_type","research update")).replace(/_/g," ").toUpperCase()} - {text(row,"exchange")}:{text(row,"symbol")}</span><strong>{text(row,"title",text(row,"update_kind",text(row,"model_key","Research update")).replace(/_/g," "))}</strong><small>{formatRelative(text(row,"effective_at",text(row,"captured_at")))} - {text(row,"status","source captured").replace(/_/g," ")}</small></div><div><a href={text(row,"thesis_href",text(row,"case_href","/research/cases?case_id="+num(row,"research_case_id")))}>Open</a>{text(row,"source_url")?<a href={text(row,"source_url")} target="_blank" rel="noreferrer">Source <ExternalLink size={12}/></a>:null}</div></article>)}</div></details>:<p className="rc-monitor__empty">No new material source or thesis change is currently recorded for followed companies.</p>}</section>
    <div className="rc-toolbar"><div><strong>{status==="blocked"?cases.length:listData?.pagination.total??0}</strong> durable cases</div><label>Show <select value={status} onChange={e=>setParams(current=>{if(e.target.value)current.set("status",e.target.value);else current.delete("status");current.delete("case_id");current.delete("page");return current;})}><option value="">All cases</option><option value="proposed">Awaiting start</option><option value="collecting">Collecting sources</option><option value="active">In progress</option><option value="review">Draft review</option><option value="blocked">Needs attention</option><option value="completed">Completed</option></select></label></div>
    {(query.isLoading||(caseId>0&&detailQuery.isLoading))?<div className="rc-loading"><Skeleton/><Skeleton/><Skeleton/></div>:!cases.length?<Empty icon={BookOpen} title="No research cases" description="Ask Charlie to start long-term research on a company or idea."/>:<div className="rc-layout"><aside className="rc-list" aria-label="Research cases">{cases.map(row=>{const id=num(row,"id"),total=num(row,"agent_total"),done=num(row,"agent_done"),displayStatus=caseStage(row),ready=num(row,"section_ready"),sectionTotal=num(row,"section_total",10);return <button type="button" key={id} className={`rc-case ${selected&&num(selected,"id")===id?"is-selected":""}`} onClick={()=>choose(id)}><div className="rc-case__top"><div><strong>{text(row,"ticker","—")}</strong><span>Case #{id}</span></div><StatusPill status={displayStatus}/></div><h3>{text(row,"company_name")}</h3><p>{text(row,"next_action")}</p><div className="rc-progress"><i style={{width:`${displayStatus==="review"?percent(ready,sectionTotal):percent(done,total)}%`}}/></div><small>{displayStatus==="review"?ready+"/"+sectionTotal+" sections review-ready":num(row,"source_job_pending")?num(row,"source_job_pending")+" sources processing":total?`${done}/${total} workstreams complete`:"Plan ready"} · {formatRelative(text(row,"updated_at"))}</small></button>;})}</aside>{selected?<CaseDetail row={selected} agents={data?.agents||[]} workItems={data?.work_items||[]} evidence={data?.evidence||[]} events={data?.events||[]} modelRuns={data?.model_runs||[]} sourceJobs={data?.source_jobs||[]} blockers={data?.blockers||[]} sections={data?.sections||[]} importedResearch={data?.imported_research||[]} busy={start.isPending||approve.isPending||prepareResume.isPending||repair.isPending||reportRepair.isPending} onStart={()=>approveAndStart(selected)} onRepair={()=>repairCase(selected)}/>:null}</div>}
  </div>;
}

function CaseDetail({row,agents,workItems,evidence,events,modelRuns,sourceJobs,blockers,sections,importedResearch,busy,onStart,onRepair}:{row:LiveRow;agents:LiveRow[];workItems:LiveRow[];evidence:LiveRow[];events:LiveRow[];modelRuns:LiveRow[];sourceJobs:LiveRow[];blockers:LiveRow[];sections:LiveRow[];importedResearch:LiveRow[];busy:boolean;onStart:()=>void;onRepair:()=>void}){
  const status=text(row,"status"),openBlockers=blockers.filter(b=>["open","retrying"].includes(text(b,"status")));
  const deliveryBlockerKeys=new Set(["report_pdf_render","research_pack_generation"]);
  const deliveryOnly=openBlockers.length>0&&openBlockers.every(blocker=>deliveryBlockerKeys.has(text(blocker,"blocker_key")));
  const hasHighBlocker=openBlockers.some(b=>["critical","high"].includes(text(b,"severity"))),requiresUserAction=openBlockers.some(b=>Boolean(text(b,"user_action"))),isRepairable=status==="blocked"||num(row,"agent_blocked")>0||num(row,"source_job_blocked")>0||requiresUserAction,hasBlockingState=isRepairable||hasHighBlocker,displayStatus=hasBlockingState?"blocked":caseStage(row),id=num(row,"id"),rate=num(row,"exchange_rate_inr_per_usd",87),estimate=num(row,"estimated_cost_usd"),hardMax=num(row,"hard_max_cost_usd"),actual=num(row,"actual_cost_usd"),sourceCount=Math.max(num(row,"source_count"),num(row,"preflight_source_count")),sectionReady=num(row,"section_ready"),sectionTotal=num(row,"section_total",10),validatedSources=num(row,"validated_source_count"),reviewDraft=status==="review"&&(sectionReady<sectionTotal||validatedSources===0);
  const currentPreflightId=num(row,"preflight_id"),currentModelRuns=currentPreflightId?modelRuns.filter(run=>num(run,"preflight_id")===currentPreflightId):modelRuns;
  const latest:Record<string,LiveRow>={}; currentModelRuns.forEach(run=>{const role=text(run,"role_key"),current=latest[role];if(!current||num(run,"iteration")>num(current,"iteration")||(num(run,"iteration")===num(current,"iteration")&&num(run,"attempt")>num(current,"attempt")))latest[role]=run;});
  const specialists=["company_business","filings","financials","management","industry_moat","valuation","bear_risk"].map(k=>latest[k]).filter(Boolean); const specialistDone=specialists.filter(r=>text(r,"status")==="completed").length;
  const stageState=status==="proposed"
    ? ["waiting","waiting","waiting","waiting","waiting","waiting"]
    : [sourceJobs.length&&sourceJobs.every(j=>text(j,"status")==="completed")?"done":sourceJobs.some(j=>["running","queued","retry_wait"].includes(text(j,"status")))?"active":sourceCount?"done":"waiting",evidence.length?"done":sourceJobs.length?"active":"waiting",specialistDone===7?"done":specialists.length?"active":"waiting",latest.lead_synthesis?.status==="completed"&&!hasBlockingState?"done":hasBlockingState?"blocked":latest.lead_synthesis?"active":"waiting",latest.independent_review?.status==="completed"&&!hasBlockingState?"done":hasBlockingState?"blocked":latest.independent_review?"active":"waiting",status==="completed"&&!hasBlockingState?"done":status==="review"?"active":hasBlockingState?"blocked":"waiting"];
  const reportCoverage=(row.report_coverage_snapshot&&typeof row.report_coverage_snapshot==="object"?row.report_coverage_snapshot:{}) as LiveRow;
  const reportContentState=text(reportCoverage,"content_state","draft").toLowerCase(),reportDeliveryState=text(reportCoverage,"delivery_state").toLowerCase();
  const reportHasEvidenceDebt=reportContentState==="evidence_debt",reportHasHtml=Boolean(text(row,"report_html_path")),reportHasPdf=Boolean(text(row,"report_pdf_path"));
  const reportStale=text(reportCoverage,"freshness_state").toLowerCase()==="superseded";
  const reportContentLabel=reportHasEvidenceDebt?"evidence-debt":reportContentState==="accepted"?"accepted":"draft";
  const reportLabel=`Open ${reportStale?"superseded ":""}${reportContentLabel} report v${num(row,"report_version")}`;
  const reportDeliveryLabel=reportDeliveryState==="pdf_ready"?"PDF unavailable — refresh report delivery":"PDF rendering / retry scheduled";
  return <main className="rc-detail"><header className="rc-detail__head"><div><span>{text(row,"exchange")}:{text(row,"ticker")} · Case #{id}</span><h2>{text(row,"company_name")}</h2><p>{text(row,"mandate")}</p></div><Badge tone={statusTone(displayStatus)}>{reviewDraft?"draft review":displayStatus.replace(/_/g," ")}</Badge></header>
    <section className="rc-next"><div><span>{hasBlockingState?(isRepairable?"REPAIR REQUIRED":"VALIDATION GATE"):reviewDraft?"DRAFT READY FOR HUMAN REVIEW":"WHAT IS HAPPENING NOW"}</span><strong>{reviewDraft?sectionReady+" of "+sectionTotal+" sections are review-ready":text(row,"next_action")}</strong><p>{reviewDraft?validatedSources+" sources are independently validated. This is a draft checkpoint, not completed research or a final investment conclusion.":text(row,"latest_event_summary",text(row,"current_goal","The case is durable and tracked here."))}</p></div><div className="rc-next__actions">{["review","completed"].includes(status)?<a className="rc-link" href={`/fundamental/theses?symbol=${encodeURIComponent(text(row,"ticker"))}`}>Open company dashboard</a>:null}{status==="proposed"?<Button variant="primary" icon={Play} disabled={busy} onClick={onStart}>{busy?"Starting…":num(row,"preflight_id")?"Review cost & start":"Ask Charlie to prepare plan"}</Button>:isRepairable?<Button variant="primary" icon={RefreshCw} disabled={busy} onClick={onRepair}>{busy?"Working…":deliveryOnly?"Repair report locally · ₹0":text(row,"preflight_status") === "approved" ? "Review blocker resolution" : text(row,"preflight_status") === "awaiting_approval" ? "Review cost & resume" : "Prepare fresh cost plan"}</Button>:null}{num(row,"report_id")&&reportHasHtml?<a className="rc-link" href={`${API_BASE_URL}/api/research/case-reports/${num(row,"report_id")}/view`}>{reportLabel}</a>:num(row,"report_id")?<span className="rc-link rc-link--quiet">Report rendering / retry scheduled</span>:null}{num(row,"report_id")&&reportHasPdf?<a className="rc-link rc-link--quiet" href={`${API_BASE_URL}/api/research/case-reports/${num(row,"report_id")}/download`}>Download PDF</a>:num(row,"report_id")&&reportHasHtml&&!reportHasPdf?<span className="rc-link rc-link--quiet" aria-label="PDF delivery status">{reportDeliveryLabel}</span>:null}</div></section>
    <section className="rc-stage-rail" aria-label="Research stages">{STAGES.map(([key,label],i)=><div key={key} className={`rc-stage is-${stageState[i]}`}><i>{stageState[i]==="done"?<CheckCircle2 size={16}/>:i+1}</i><div><strong>{label}</strong><span>{stageState[i]==="done"?"Complete":stageState[i]==="active"?"Working":stageState[i]==="blocked"?"Blocked":"Waiting"}</span></div></div>)}</section>
    <div className="rc-metrics"><div><span>{status==="proposed"?"Linked source candidates":"Qualified official sources"}</span><strong>{sourceCount}</strong><small>{status==="proposed"?"Collection and validation begin only after Start":`${num(row,"source_job_pending")} processing · ${num(row,"validated_fact_count")} financial facts validated`}</small></div><div><span>Research pack</span><strong>{sectionReady} / {sectionTotal}</strong><small>review-ready draft sections</small></div><div><span>Model budget</span><strong>Prior runs ₹{(actual*rate).toFixed(2)}</strong><small>next estimate ₹{(estimate*rate).toFixed(2)} · hard stop ₹{(hardMax*rate).toFixed(2)}</small></div><div><span>Decision state</span><strong>{text(row,"decision_readiness","needs research").replace(/_/g," ")}</strong><small>{text(row,"horizon")} · {text(row,"priority")} priority</small></div></div>
    {(openBlockers.length||isRepairable)?<section className="rc-section rc-blockers"><div className="rc-section__title"><div><span>NEEDS ATTENTION</span><h3>Exact blockers and repair path</h3></div><Badge tone="risk">{openBlockers.length||1}</Badge></div>{openBlockers.length?openBlockers.map(blocker=>{const copy=blockerCopy(blocker);return <article key={num(blocker,"id")}><AlertTriangle size={18}/><div><strong>{text(blocker,"title")}</strong><p>{copy.summary}</p><dl><div><dt>Stack action</dt><dd>{text(blocker,"system_action","The failed stage is preserved for bounded repair.")}</dd></div><div><dt>Your action</dt><dd>{text(blocker,"user_action",copy.nextAction)}</dd></div></dl>{copy.technical?<details><summary>Technical detail</summary><code>{copy.technical}</code></details>:null}</div><StatusPill status={text(blocker,"status")}/></article>}):<article><AlertTriangle size={18}/><div><strong>This case stopped before the next research stage</strong><p>{text(row,"latest_event_summary","The prior attempt was preserved and no further paid work will run until you review the repair plan.")}</p><dl><div><dt>Stack action</dt><dd>Preserve completed work, re-check qualified sources and prepare a bounded retry for the failed stage.</dd></div><div><dt>Your action</dt><dd>Review the proposed repair scope and cost boundary before resuming.</dd></div></dl></div><StatusPill status="blocked"/></article>}<div className="rc-repair-footer"><div><strong>{deliveryOnly?"Local report delivery repair":"Repair keeps completed work"}</strong><p>{deliveryOnly?"Re-render the saved pack at INR 0 with no source or model rerun.":"Only the failed stage is retried. Review the cost boundary before any paid model call."}</p></div><Button variant="primary" icon={RefreshCw} disabled={busy} onClick={onRepair}>{busy?"Preparing repair...":deliveryOnly?"Repair report delivery · ₹0":"Review repair plan"}</Button></div></section>:null}
    <details className="rc-operations"><summary><div><UsersRound size={17}/><span>Research operations, analyst work and activity</span></div><Badge tone="default">{agents.length} workstreams</Badge></summary><div className="rc-operations__body">
    <section className="rc-section"><div className="rc-section__title"><div><span>COMPLETE COMPANY PACK</span><h3>What the finished research will contain</h3></div><Badge tone="default">{sections.length||10} sections</Badge></div><div className="rc-pack-grid">{sections.map(section=><article key={num(section,"id")}><div><FileCheck2 size={16}/><strong>{text(section,"title")}</strong></div><StatusPill status={text(section,"status")}/><p>{text(section,"summary",arrLen(section,"coverage_gaps")?`${arrLen(section,"coverage_gaps")} evidence gaps remain.`:"The assigned analyst will populate this from cited sources.")}</p></article>)}</div></section>
    <section className="rc-section"><div className="rc-section__title"><div><span>ANALYST TEAM</span><h3>Current workstreams</h3></div><Badge tone="default">{agents.length}</Badge></div><div className="rc-workstreams">{agents.map(agent=>{const item=workItems.find(w=>text(w,"owner_agent")===text(agent,"agent_name"));return <article key={num(agent,"id")}><div><UsersRound size={16}/><strong>{ROLE_LABELS[text(agent,"role_key")]||text(agent,"agent_name")}</strong></div><StatusPill status={text(agent,"status")}/><p>{item?text(item,"objective"):text(agent,"status")==="completed"?"Cited artifact delivered.":"Durable assignment waiting on its dependency."}</p></article>;})}</div></section>
    <section className="rc-section"><div className="rc-section__title"><div><span>ACTIVITY</span><h3>Plain-English progress</h3></div></div><div className="rc-timeline">{events.slice(0,10).map(event=><article key={num(event,"id")}><i/><div><strong>{text(event,"event_summary",text(event,"event_type").replace(/_/g," "))}</strong><span>{text(event,"actor")} · {formatRelative(text(event,"occurred_at"))}</span></div></article>)}</div></section>
    </div></details>
    <details className="rc-evidence"><summary><div><FileText size={17}/><span>Evidence library, extraction & review</span></div><Badge tone="default">{evidence.length} linked · {sourceJobs.length} source jobs</Badge></summary><div className="rc-evidence__body"><h4>Official-source collection</h4>{sourceJobs.map(job=><article key={num(job,"id")}><div><strong>{text(job,"source_title",text(job,"job_kind").replace(/_/g," "))}</strong><span>{text(job,"filed_at","Date unavailable")} · attempt {num(job,"attempt")}/{num(job,"max_attempts")}</span></div><StatusPill status={text(job,"status")}/></article>)}<h4>Linked evidence</h4>{evidence.map(source=><article key={num(source,"id")}><div><strong>{text(source,"source_kind","Source").replace(/_/g," ")}</strong><span>{text(source,"validation_status",text(source,"parser_status"))} · {text(source,"publication_date",text(source,"captured_at"))}</span></div>{text(source,"source_url")?<a href={text(source,"source_url")} target="_blank" rel="noreferrer">Open source <ExternalLink size={13}/></a>:<span>Local SSD artifact</span>}</article>)}<h4>Prior user research</h4>{importedResearch.length?importedResearch.map(item=><article key={num(item,"id")}><div><strong>{text(item,"title",text(item,"original_filename"))}</strong><span>{text(item,"source_posture").replace(/_/g," ")} · {text(item,"review_status").replace(/_/g," ")}</span></div><span>{text(item,"artifact_kind").replace(/_/g," ")}</span></article>):<p>No mapped historical user research for this company.</p>}<h4>Model receipts</h4>{modelRuns.map(run=><article key={num(run,"id")}><div><strong>{ROLE_LABELS[text(run,"role_key")]||text(run,"agent_name")}</strong><span>{text(run,"provider")} / {text(run,"model_name")} · ${num(run,"actual_cost_usd").toFixed(4)}</span></div><StatusPill status={text(run,"status")}/></article>)}</div></details>
  </main>;
}
