export const ResearchDeskCss = String.raw`.rd-page{min-height:100%;padding-bottom:48px;background:var(--bg);color:var(--text)}
.rd-hero{display:grid;grid-template-columns:minmax(0,1.35fr) minmax(340px,.65fr);gap:34px;align-items:end;padding:36px 40px 28px;background:linear-gradient(135deg,var(--surface) 0%,var(--surface-soft) 100%);border-bottom:1px solid var(--border)}
.rd-hero--single{grid-template-columns:1fr}
.rd-eyebrow{display:block;margin-bottom:8px;color:var(--accent);font:800 11px/1.2 var(--font-body);letter-spacing:.14em;text-transform:uppercase}
.rd-hero h1{max-width:900px;margin:0;color:var(--text);font:700 clamp(34px,4.2vw,58px)/1.02 var(--font-display)}
.rd-hero p{max-width:820px;margin:12px 0 0;color:var(--text-muted);font-size:15px;line-height:1.58}
.rd-command{display:flex;align-items:center;gap:10px;padding:7px 7px 7px 14px;background:var(--surface);border:1px solid var(--border);border-radius:var(--radius-lg);box-shadow:var(--shadow-2)}
.rd-command>svg{flex:0 0 auto;color:var(--accent)}
.rd-command input{min-width:0;flex:1;padding:12px 2px;border:0;outline:0;background:transparent;color:var(--text);font:inherit}
.rd-command button{display:inline-flex;align-items:center;gap:7px;min-height:42px;padding:0 15px;border:0;border-radius:var(--radius-sm);background:var(--accent);color:var(--text-on-accent);font-weight:750;cursor:pointer;white-space:nowrap}
.rd-nav{position:sticky;top:0;z-index:6;display:flex;gap:4px;overflow-x:auto;padding:11px 40px;background:color-mix(in srgb,var(--surface) 94%,transparent);border-bottom:1px solid var(--border);backdrop-filter:blur(14px)}
.rd-nav__item{display:inline-flex;align-items:center;gap:7px;padding:9px 12px;border-radius:var(--radius-sm);color:var(--text-muted);font-size:12px;font-weight:750;text-decoration:none;white-space:nowrap}
.rd-nav__item:hover{background:var(--surface-soft);color:var(--text)}
.rd-nav__item.is-active{background:var(--accent-soft);color:var(--accent)}
.rd-safety{display:flex;flex-wrap:wrap;gap:8px 22px;padding:11px 40px;border-bottom:1px solid var(--border);background:var(--surface);color:var(--text-muted);font-size:11px}
.rd-safety span{display:inline-flex;align-items:center;gap:6px}.rd-safety span:first-child{color:var(--status-ok);font-weight:750}
.rd-body{display:grid;gap:18px;padding:24px 40px 0}.rd-body--two{grid-template-columns:minmax(0,1.35fr) minmax(300px,.65fr)}
.rd-section{min-width:0;overflow:hidden;border:1px solid var(--border);border-radius:var(--radius-lg);background:var(--surface);box-shadow:var(--shadow-1)}
.rd-section__head{display:flex;justify-content:space-between;align-items:flex-start;gap:20px;padding:18px 20px;border-bottom:1px solid var(--border-subtle)}
.rd-section__head h2{margin:3px 0 0;font:700 21px/1.2 var(--font-display);color:var(--text)}
.rd-section__head p{max-width:700px;margin:5px 0 0;color:var(--text-muted);font-size:12px;line-height:1.45}
.rd-section__head>a,.rd-link{display:inline-flex;align-items:center;gap:5px;color:var(--accent);font-size:12px;font-weight:750;text-decoration:none;white-space:nowrap}
.rd-kicker{color:var(--accent);font-size:10px;font-weight:800;letter-spacing:.12em;text-transform:uppercase}
.rd-metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));border-bottom:1px solid var(--border)}
.rd-metric{padding:18px 20px;border-right:1px solid var(--border)}.rd-metric:last-child{border-right:0}.rd-metric span,.rd-metric small{display:block;color:var(--text-muted);font-size:11px}.rd-metric strong{display:block;margin:6px 0 4px;font:700 27px/1 var(--font-display);font-variant-numeric:tabular-nums}.rd-metric.is-attention strong{color:var(--status-risk)}
.rd-list{display:grid}.rd-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px 20px;padding:15px 20px;border-top:1px solid var(--border-subtle);color:inherit;text-decoration:none}.rd-row:first-child{border-top:0}.rd-row:hover{background:var(--surface-soft)}
.rd-row__meta{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin-bottom:5px;color:var(--text-muted);font-size:10px;text-transform:uppercase;letter-spacing:.06em}.rd-row h3{margin:0;color:var(--text);font-size:14px;line-height:1.35}.rd-row p{margin:5px 0 0;color:var(--text-muted);font-size:12px;line-height:1.45}.rd-row__aside{display:grid;align-content:center;justify-items:end;gap:6px;color:var(--text-muted);font-size:10px;white-space:nowrap}
.rd-state{display:flex;align-items:flex-start;gap:12px;padding:20px;color:var(--text-muted)}.rd-state svg{flex:0 0 auto;color:var(--accent)}.rd-state strong{display:block;color:var(--text);font-size:13px}.rd-state p{margin:4px 0 0;font-size:12px;line-height:1.45}.rd-state--error{background:var(--status-risk-soft)}.rd-state--error svg{color:var(--status-risk)}.rd-state button{margin-top:10px;padding:7px 10px;border:1px solid var(--border);border-radius:var(--radius-sm);background:var(--surface);color:var(--text);cursor:pointer}
.rd-skeletons{display:grid;gap:10px;padding:18px}.rd-skeletons>*{height:74px}
.rd-refresh{display:inline-flex;align-items:center;gap:6px;color:var(--text-muted);font-size:10px}.rd-refresh svg{animation:rd-spin 1s linear infinite}@keyframes rd-spin{to{transform:rotate(360deg)}}
.rd-follow-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;padding:16px}.rd-follow-card{display:grid;gap:11px;padding:16px;border:1px solid var(--border-subtle);border-radius:var(--radius-md);background:var(--surface-soft)}.rd-follow-card__top{display:flex;justify-content:space-between;align-items:start;gap:12px}.rd-follow-card__top strong{font:700 20px/1 var(--font-display)}.rd-follow-card__top span{display:block;margin-top:5px;color:var(--text-muted);font-size:11px}.rd-follow-card p{margin:0;color:var(--text-muted);font-size:12px;line-height:1.45}.rd-follow-card__links{display:flex;gap:14px;flex-wrap:wrap}.rd-follow-card__links a{color:var(--accent);font-size:11px;font-weight:750;text-decoration:none}
.rd-filterbar{display:flex;align-items:end;gap:10px;flex-wrap:wrap;padding:14px 20px;border-bottom:1px solid var(--border-subtle);background:var(--surface-soft)}.rd-filterbar label{display:grid;gap:5px;color:var(--text-muted);font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.06em}.rd-filterbar input,.rd-filterbar select{min-height:36px;padding:0 10px;border:1px solid var(--border);border-radius:var(--radius-sm);background:var(--surface);color:var(--text)}.rd-filterbar input{min-width:260px}.rd-filterbar button{min-height:36px;padding:0 13px;border:0;border-radius:var(--radius-sm);background:var(--accent);color:var(--text-on-accent);font-weight:750;cursor:pointer}
.rd-pages{display:flex;justify-content:space-between;align-items:center;padding:14px 20px;border-top:1px solid var(--border-subtle);color:var(--text-muted);font-size:11px}.rd-pages button{padding:7px 10px;border:1px solid var(--border);border-radius:var(--radius-sm);background:var(--surface);color:var(--text);cursor:pointer}.rd-pages button:disabled{opacity:.45;cursor:not-allowed}
.rd-scan-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;padding:16px}.rd-scan{display:grid;gap:10px;padding:16px;border:1px solid var(--border-subtle);border-radius:var(--radius-md);background:var(--surface-soft)}.rd-scan__head{display:flex;justify-content:space-between;gap:12px}.rd-scan__head strong{font-size:15px}.rd-scan__head span{color:var(--accent);font-size:10px;font-weight:800;text-transform:uppercase}.rd-scan p{margin:0;color:var(--text-muted);font-size:12px;line-height:1.5}.rd-scan footer{display:flex;justify-content:space-between;align-items:center;gap:10px;color:var(--text-muted);font-size:10px}
.rd-scan footer button.rd-link{padding:0;border:0;background:transparent;cursor:pointer}
.rd-source-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr)) auto;gap:12px;align-items:end;padding:18px 20px;border-bottom:1px solid var(--border-subtle);background:var(--surface-soft)}.rd-source-form label,.rd-scanner-builder label{display:grid;gap:6px;color:var(--text-muted);font-size:10px;font-weight:800;letter-spacing:.06em;text-transform:uppercase}.rd-source-form input,.rd-scanner-builder textarea{width:100%;box-sizing:border-box;padding:10px 11px;border:1px solid var(--border);border-radius:var(--radius-sm);outline:0;background:var(--surface);color:var(--text);font:inherit}.rd-source-form input:focus,.rd-scanner-builder textarea:focus{border-color:var(--accent);box-shadow:0 0 0 3px var(--accent-soft)}.rd-source-form__wide{grid-column:1/-2}.rd-source-form .rd-check{display:flex;grid-column:1/-2;align-items:flex-start;gap:8px;font-weight:600;line-height:1.45;letter-spacing:0;text-transform:none}.rd-source-form .rd-check input{width:auto;margin-top:2px}.rd-source-form>button,.rd-scanner-builder>button{display:inline-flex;align-items:center;justify-content:center;gap:7px;min-height:39px;padding:0 14px;border:0;border-radius:var(--radius-sm);background:var(--accent);color:var(--text-on-accent);font-weight:800;cursor:pointer}.rd-source-form>button:disabled,.rd-scanner-builder>button:disabled{opacity:.5;cursor:not-allowed}
.rd-source-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;padding:16px}.rd-source-card{display:grid;gap:9px;padding:15px;border:1px solid var(--border-subtle);border-radius:var(--radius-md);background:var(--surface-soft)}.rd-source-card strong{display:block;font-size:13px}.rd-source-card>div span,.rd-source-card p,.rd-source-card footer{color:var(--text-muted);font-size:10px;line-height:1.45}.rd-source-card p{margin:0}.rd-source-card>a{color:var(--accent);font-size:11px;font-weight:750;text-decoration:none}.rd-source-card footer{display:flex;justify-content:space-between;align-items:center;gap:10px}.rd-source-card button{display:inline-flex;align-items:center;gap:5px;padding:6px 8px;border:1px solid var(--border);border-radius:var(--radius-sm);background:var(--surface);color:var(--text);cursor:pointer}.rd-method{border-top:1px solid var(--border-subtle)}.rd-method>summary{display:flex;align-items:center;gap:8px;padding:13px 20px;color:var(--text-muted);font-size:11px;font-weight:750;cursor:pointer}.rd-method[open]>summary{background:var(--surface-soft);color:var(--text)}
.rd-inline-detail{padding:8px 10px;border:1px solid color-mix(in srgb,var(--status-risk) 30%,var(--border));border-radius:var(--radius-sm);background:var(--status-risk-soft)}.rd-inline-detail summary{color:var(--status-risk);font-size:10px;font-weight:800;cursor:pointer}.rd-inline-detail p{margin:7px 0 0;color:var(--text);overflow-wrap:anywhere}
.rd-scanner-builder{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px;align-items:end;padding:18px 20px;background:var(--surface-soft)}.rd-scanner-builder textarea{resize:vertical;line-height:1.5}.rd-formula-strip{display:flex;gap:7px;align-items:center;flex-wrap:wrap;padding:10px 20px;border-top:1px solid var(--border-subtle);border-bottom:1px solid var(--border-subtle);color:var(--text-muted);font-size:10px}.rd-formula-strip span{font-weight:800;text-transform:uppercase;letter-spacing:.06em}.rd-formula-strip code{padding:4px 7px;border-radius:999px;background:var(--accent-soft);color:var(--accent);font:700 10px/1 var(--font-body)}.rd-scan--workflow{background:var(--surface)}.rd-scan__head>div span{display:block;margin-top:4px}.rd-validation-line{display:flex;gap:6px;flex-wrap:wrap}.rd-validation-line span{padding:4px 6px;border:1px solid var(--border);border-radius:999px;color:var(--text-muted);font-size:9px}.rd-validation-line span.is-pass{border-color:color-mix(in srgb,var(--status-ok) 35%,var(--border));background:var(--status-ok-soft);color:var(--status-ok)}.rd-actions{display:flex;gap:6px;flex-wrap:wrap;justify-content:flex-end}.rd-actions button{padding:6px 8px;border:1px solid var(--border);border-radius:var(--radius-sm);background:var(--surface);color:var(--accent);font-weight:750;cursor:pointer}.rd-actions button:disabled{opacity:.5}
.rd-knowledge-list{display:grid}.rd-artifact{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px 18px;padding:15px 20px;border-top:1px solid var(--border-subtle)}.rd-artifact:first-child{border-top:0}.rd-artifact h3{margin:0;font-size:13px}.rd-artifact p{margin:5px 0 0;color:var(--text-muted);font-size:11px;line-height:1.45}.rd-artifact__meta{display:flex;gap:7px;flex-wrap:wrap;margin-top:8px;color:var(--text-muted);font-size:10px}.rd-artifact button{align-self:center;padding:7px 10px;border:1px solid var(--border);border-radius:var(--radius-sm);background:var(--surface);color:var(--accent);font-weight:750;cursor:pointer}
.rd-lineage{display:grid;gap:8px;padding:16px}.rd-lineage article{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;padding:12px;border-left:3px solid var(--accent);background:var(--surface-soft)}.rd-lineage strong{font-size:12px}.rd-lineage span{color:var(--text-muted);font-size:10px}
@media(max-width:980px){.rd-hero,.rd-body--two{grid-template-columns:1fr}.rd-hero{align-items:start}.rd-metrics{grid-template-columns:repeat(2,1fr)}.rd-metric:nth-child(2){border-right:0}.rd-metric:nth-child(-n+2){border-bottom:1px solid var(--border)}.rd-follow-grid,.rd-scan-list{grid-template-columns:1fr}.rd-source-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(max-width:620px){.rd-hero{padding:26px 16px 20px}.rd-hero h1{font-size:36px}.rd-command{align-items:stretch;flex-wrap:wrap}.rd-command input{width:calc(100% - 32px)}.rd-command button{width:100%;justify-content:center}.rd-nav{padding:9px 16px}.rd-safety{padding:10px 16px}.rd-body{padding:16px 16px 0}.rd-metric{padding:14px}.rd-section__head{align-items:flex-start;flex-direction:column}.rd-row,.rd-artifact{grid-template-columns:1fr}.rd-row__aside{justify-items:start}.rd-filterbar{align-items:stretch;flex-direction:column}.rd-filterbar label,.rd-filterbar input,.rd-filterbar select,.rd-filterbar button{width:100%}.rd-filterbar input{min-width:0}.rd-follow-grid,.rd-scan-list,.rd-source-grid{grid-template-columns:1fr;padding:12px}.rd-artifact button{justify-self:start}.rd-source-form,.rd-scanner-builder{grid-template-columns:1fr}.rd-source-form__wide,.rd-source-form .rd-check{grid-column:auto}.rd-source-form>button,.rd-scanner-builder>button{width:100%}.rd-scan footer,.rd-source-card footer{align-items:flex-start;flex-direction:column}.rd-actions{justify-content:flex-start}}
@media(prefers-reduced-motion:reduce){.rd-refresh svg{animation:none}}`;
