INSERT INTO agent.tool_registry (tool_name, tool_type, owning_agent, permission_level, enabled, description, config)
VALUES
    ('ai_os_control_plane_snapshot', 'mcp_tool', 'Jarvis', 'read_only', true, 'Read the full AI OS control-plane snapshot.', '{"surface":"mcp"}'::jsonb),
    ('ai_os_orchestration_stack', 'mcp_tool', 'Charlie Munger', 'read_only', true, 'Read active orchestrator/runtime/specialist agent stack.', '{"surface":"mcp"}'::jsonb),
    ('ai_os_list_active_agents', 'mcp_tool', 'Jarvis', 'read_only', true, 'List active agent profiles and routes.', '{"surface":"mcp"}'::jsonb),
    ('ai_os_list_open_tasks', 'mcp_tool', 'Jarvis', 'read_only', true, 'List open agent tasks.', '{"surface":"mcp"}'::jsonb),
    ('ai_os_p2cursor_source_summary', 'mcp_tool', 'Data Steward', 'read_only', true, 'Read p2cursor source summary.', '{"surface":"mcp"}'::jsonb),
    ('ai_os_algo_import_summary', 'mcp_tool', 'Data Steward', 'read_only', true, 'Read algo trading import summary.', '{"surface":"mcp"}'::jsonb),
    ('ai_os_component_inventory', 'mcp_tool', 'Coding Lead Agent', 'read_only', true, 'Read reusable component inventory.', '{"surface":"mcp"}'::jsonb),
    ('ai_os_source_requirements', 'mcp_tool', 'Coding Lead Agent', 'read_only', true, 'Read parsed source requirements.', '{"surface":"mcp"}'::jsonb),
    ('ai_os_client_3081282_summary', 'mcp_tool', 'Portfolio Manager', 'read_only', true, 'Read imported client 3081282 summary.', '{"surface":"mcp"}'::jsonb),
    ('ai_os_client_3081282_symbol_dates', 'mcp_tool', 'Portfolio Manager', 'read_only', true, 'Read symbol-level buy/sell dates for client 3081282.', '{"surface":"mcp"}'::jsonb),
    ('ai_os_client_3081282_trade_timeline', 'mcp_tool', 'Portfolio Manager', 'read_only', true, 'Read client 3081282 trade timeline.', '{"surface":"mcp"}'::jsonb),
    ('ai_os_research_outputs', 'mcp_tool', 'Research Lead', 'read_only', true, 'Search indexed AI research outputs.', '{"surface":"mcp"}'::jsonb),
    ('ai_os_research_output_detail', 'mcp_tool', 'Research Lead', 'read_only', true, 'Read one research output detail.', '{"surface":"mcp"}'::jsonb),
    ('ai_os_fincept_component_review', 'mcp_tool', 'Codex', 'read_only', true, 'Read Fincept component review.', '{"surface":"mcp"}'::jsonb),
    ('ai_os_fincept_install_status', 'mcp_tool', 'Codex', 'read_only', true, 'Read Fincept install/build status.', '{"surface":"mcp"}'::jsonb),
    ('ai_os_search_obsidian_notes', 'mcp_tool', 'Knowledge Librarian', 'read_only', true, 'Search indexed Obsidian notes.', '{"surface":"mcp"}'::jsonb),
    ('ai_os_recent_trading_signals', 'mcp_tool', 'Trading Desk', 'read_only', true, 'Read recent trading signals.', '{"surface":"mcp"}'::jsonb),
    ('ai_os_latest_positions', 'mcp_tool', 'Portfolio Manager', 'read_only', true, 'Read latest imported positions.', '{"surface":"mcp"}'::jsonb),
    ('ai_os_reindex_obsidian', 'mcp_tool', 'Knowledge Librarian', 'write_db_only', true, 'Reindex Obsidian metadata into Postgres.', '{"writes":["knowledge.obsidian_notes","knowledge.note_links"]}'::jsonb),
    ('ai_os_upsert_client', 'mcp_tool', 'Portfolio Manager', 'write_db_manual_only', true, 'Create or update local client/account records.', '{"writes":["portfolio.clients","portfolio.accounts"]}'::jsonb),
    ('ai_os_stage_holding_update', 'mcp_tool', 'Portfolio Manager', 'write_db_manual_only', true, 'Stage a manual holding update.', '{"writes":["portfolio.manual_holding_updates"]}'::jsonb),
    ('ai_os_apply_holding_update', 'mcp_tool', 'Portfolio Manager', 'write_db_manual_only', true, 'Apply a staged holding update to local positions.', '{"writes":["portfolio.positions"]}'::jsonb),
    ('ai_os_mcp_capabilities', 'mcp_tool', 'Jarvis', 'read_only', true, 'List current MCP tools, permissions, owners, and guardrails.', '{"surface":"mcp"}'::jsonb),
    ('ai_os_mcp_audit_log', 'mcp_tool', 'Risk Agent', 'read_only', true, 'Read recent MCP write/read audit events.', '{"surface":"mcp"}'::jsonb),
    ('ai_os_create_task', 'mcp_tool', 'Jarvis', 'write_with_approval', true, 'Create an agent task and optional inbox item.', '{"writes":["agent.tasks","agent.inbox_items"]}'::jsonb),
    ('ai_os_update_task_status', 'mcp_tool', 'Jarvis', 'write_with_approval', true, 'Update agent task status, evidence, and output path.', '{"writes":["agent.tasks"]}'::jsonb),
    ('ai_os_list_inbox', 'mcp_tool', 'Jarvis', 'read_only', true, 'List agent inbox items with task linkage and evidence.', '{"reads":["agent.inbox_items"]}'::jsonb),
    ('ai_os_update_inbox_status', 'mcp_tool', 'Jarvis', 'write_with_approval', true, 'Update one inbox item status and action text.', '{"writes":["agent.inbox_items"]}'::jsonb),
    ('ai_os_create_approval', 'mcp_tool', 'Risk Agent', 'write_with_approval', true, 'Create a human approval request.', '{"writes":["agent.approvals"]}'::jsonb),
    ('ai_os_decide_approval', 'mcp_tool', 'Risk Agent', 'write_with_approval', true, 'Approve or reject a pending approval.', '{"writes":["agent.approvals"]}'::jsonb),
    ('ai_os_create_research_idea', 'mcp_tool', 'Research Lead', 'write_with_approval', true, 'Create a research idea with evidence.', '{"writes":["research.ideas"]}'::jsonb),
    ('ai_os_record_raw_artifact', 'mcp_tool', 'Data Steward', 'write_db_manual_only', true, 'Register a raw artifact or browser/public-source output.', '{"writes":["core.raw_artifacts"]}'::jsonb),
    ('ai_os_write_obsidian_note', 'mcp_tool', 'Knowledge Librarian', 'write_with_approval', true, 'Write approved markdown output into structured Obsidian folders and reindex.', '{"writes":["knowledge.obsidian_notes","filesystem:ai memory"]}'::jsonb),
    ('ai_os_start_browser_run', 'mcp_tool', 'Browser Research Runner', 'browser_read', true, 'Create a browser run request/log row.', '{"writes":["ops.browser_runs"],"external_browser_control":false}'::jsonb),
    ('ai_os_complete_browser_run', 'mcp_tool', 'Browser Research Runner', 'browser_capture', true, 'Complete a browser run with captured evidence.', '{"writes":["ops.browser_runs","core.raw_artifacts"]}'::jsonb),
    ('ai_os_browser_runs', 'mcp_tool', 'Browser Research Runner', 'read_only', true, 'List browser run queue/history.', '{"reads":["ops.browser_runs"]}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    tool_type = EXCLUDED.tool_type,
    owning_agent = EXCLUDED.owning_agent,
    permission_level = EXCLUDED.permission_level,
    enabled = EXCLUDED.enabled,
    description = EXCLUDED.description,
    config = EXCLUDED.config;
