INSERT INTO ops.tradingview_action_templates (
    template_key, template_name, category, action_kind, default_exchange,
    default_timeframe, default_chart_layout, requires_symbol, approval_required,
    execution_mode, status, owner_agent, description, risk_notes, default_payload
)
VALUES
    ('technical_indicator_stack', 'Technical Indicator Stack', 'indicators', 'indicator_layout_request', 'NSE', '15', 'price_volume_indicator_stack', true, true, 'human_gated_request', 'gated', 'Technical Analyst', 'Build price, volume, VWAP, RSI, MACD, ATR, and Supertrend panes with configurable parameters.', 'Changes the signed-in TradingView chart layout. Human approval remains required until indicator-dialog automation is deterministic.', '{"panes":[{"type":"price","overlays":["VWAP","Supertrend"]},{"type":"volume"},{"type":"indicator","indicators":["RSI","MACD","ATR"]}],"parameters":{"RSI.length":14,"ATR.length":14},"broker_order_allowed":false}'::jsonb),
    ('relative_strength_ratio_chart', 'Relative Strength Ratio Chart', 'formula', 'formula_chart_request', 'NSE', 'D', 'ratio_with_benchmark', true, true, 'human_gated_request', 'gated', 'Technical Analyst', 'Open a formula chart comparing a security with a benchmark or peer, plus trend and momentum confirmation.', 'Formula symbols must be validated for exchange syntax before changing chart state.', '{"formula":"{symbol}/{benchmark}","requires":["symbol","benchmark"],"overlays":["EMA 20","EMA 50"],"broker_order_allowed":false}'::jsonb),
    ('spread_pair_formula_chart', 'Spread And Pair Formula Chart', 'formula', 'formula_chart_request', 'NSE', '60', 'spread_pair_diagnostics', true, true, 'human_gated_request', 'gated', 'Quant Agent', 'Build spread, ratio, z-score, correlation, and rolling-beta diagnostics for a two-leg pair.', 'Research view only. Formula correctness, corporate actions, and contract multipliers require validation.', '{"formulas":["{leg_a}-{hedge_ratio}*{leg_b}","{leg_a}/{leg_b}"],"indicators":["Z-Score","Correlation Coefficient","Linear Regression"],"requires":["leg_a","leg_b","hedge_ratio"],"broker_order_allowed":false}'::jsonb),
    ('option_straddle_four_pane', 'Option Straddle Four Pane', 'options', 'option_straddle_layout_request', 'NSE', '5', 'option_straddle_four_chart', true, true, 'human_gated_request', 'gated', 'Options Overlay Agent', 'Build synchronized panes for underlying, call, put, and synthetic straddle with OI/IV context.', 'Exact expiry and option symbols are mandatory. This creates charts only and never places orders.', '{"panes":["underlying","call","put","call_plus_put_formula"],"requires":["underlying","expiry","strike","call_symbol","put_symbol"],"indicators":["VWAP","Volume","Open Interest"],"sync_crosshair":true,"sync_time":true,"broker_order_allowed":false}'::jsonb),
    ('fundamental_ratio_dashboard', 'Fundamental Ratio Dashboard', 'fundamental', 'fundamental_chart_request', 'NSE', '3M', 'fundamental_ratio_multi_pane', true, true, 'human_gated_request', 'gated', 'Fundamental Analyst', 'Build quarterly and annual sales, earnings, margins, ROCE, leverage, valuation, and price overlays when TradingView financial fields are available.', 'Financial-field availability differs by exchange and symbol. Source values must be cross-checked against filings.', '{"fields":["TOTAL_REVENUE","NET_INCOME","OPERATING_MARGIN","RETURN_ON_INVESTED_CAPITAL","TOTAL_DEBT","PRICE_EARNINGS","PRICE_BOOK"],"periods":["FQ","FY"],"filing_cross_check_required":true,"broker_order_allowed":false}'::jsonb),
    ('market_regime_four_pane', 'Market Regime Four Pane', 'macro', 'multi_symbol_layout_request', 'NSE', 'D', 'market_regime_four_pane', true, true, 'human_gated_request', 'gated', 'Macro Researcher', 'Build synchronized equity index, volatility, bond yield, and USD/INR panes for regime review.', 'Symbols vary by TradingView data entitlement. Read-only research layout.', '{"panes":["equity_index","volatility_index","bond_yield","currency"],"sync_crosshair":true,"sync_time":true,"broker_order_allowed":false}'::jsonb)
ON CONFLICT (template_key) DO UPDATE SET
    template_name=EXCLUDED.template_name, category=EXCLUDED.category, action_kind=EXCLUDED.action_kind,
    default_exchange=EXCLUDED.default_exchange, default_timeframe=EXCLUDED.default_timeframe,
    default_chart_layout=EXCLUDED.default_chart_layout, requires_symbol=EXCLUDED.requires_symbol,
    approval_required=EXCLUDED.approval_required, execution_mode=EXCLUDED.execution_mode,
    status=EXCLUDED.status, owner_agent=EXCLUDED.owner_agent, description=EXCLUDED.description,
    risk_notes=EXCLUDED.risk_notes, default_payload=EXCLUDED.default_payload, updated_at=now();

UPDATE agent.tool_registry
SET config = config || '{"advanced_templates_v1":true,"indicator_stacks":true,"ratio_formula_charts":true,"pair_spread_charts":true,"option_four_pane":true,"fundamental_ratio_dashboard":true,"market_regime_layout":true,"pane_mutations_human_gated":true}'::jsonb
WHERE tool_name = 'ai_os_execute_tradingview_template_action';
