BEGIN;

INSERT INTO agent.skills (
    skill_key, skill_name, skill_family, skill_type, owner_department, status,
    execution_mode, permission_level, trigger_phrases, input_sources,
    output_targets, required_tools, risk_notes, prompt_template, config
) VALUES
    ('tradingagents_checkpointed_committee', 'Checkpointed Research Committee', 'tradingagents', 'research_committee', 'research', 'active', 'internal_workflow', 'read_only', ARRAY['run research committee','resume committee','debate this thesis'], ARRAY['research evidence packet','agent worker outputs','point-in-time market snapshot'], ARRAY['agent.agent_messages','agent.worker_runs','knowledge.obsidian_notes'], ARRAY['agent_mailbox_router','postgres_read_model'], 'A resumed committee must preserve its original as-of timestamp and evidence packet. It cannot place or size orders.', 'Run independent analyst, bull, bear, and risk passes with typed handoffs. Checkpoint each stage, preserve dissent, and end with approve-for-more-research, abstain, reject, or human-review-required.', '{"source_repo":"https://github.com/TauricResearch/TradingAgents","license":"Apache-2.0","adoption":"pattern","version_reviewed":"0.2.5","evidence":["tradingagents/graph/checkpointer.py","tradingagents/graph/setup.py","tradingagents/agents/schemas.py"],"broker_order_allowed":false}'::jsonb),
    ('tradingagents_outcome_reflection', 'Outcome-Grounded Decision Reflection', 'tradingagents', 'decision_review', 'portfolio', 'active', 'internal_workflow', 'read_only', ARRAY['review past decision','decision reflection','what did we learn'], ARRAY['immutable decision record','realized return','benchmark return','original evidence packet'], ARRAY['knowledge.obsidian_notes','strategy.validation_reviews','agent.inbox_items'], ARRAY['postgres_read_model','obsidian_writeback'], 'Reflections may update lessons and review status, never rewrite the original thesis, evidence, or decision.', 'Compare the original point-in-time decision with realized outcome and benchmark alpha. Separate process quality from luck, record calibration errors, and create a bounded follow-up task.', '{"source_repo":"https://github.com/TauricResearch/TradingAgents","license":"Apache-2.0","adoption":"pattern","evidence":["tradingagents/graph/reflection.py","tradingagents/graph/trading_graph.py","tradingagents/agents/utils/memory.py"]}'::jsonb),
    ('tradingagents_point_in_time_benchmarking', 'Point-In-Time Non-US Benchmark Review', 'tradingagents', 'validation_contract', 'quant', 'active', 'deterministic_contract', 'read_only', ARRAY['benchmark this idea','date fidelity','non us alpha'], ARRAY['exchange-qualified symbol','as-of date','market calendar','benchmark mapping'], ARRAY['strategy.validation_reviews','strategy.performance_snapshots'], ARRAY['postgres_read_model','data_quality_gate'], 'Reject future-dated fundamentals, news, prices, and benchmark observations. Benchmark choice must be explicit.', 'Validate date fidelity, exchange-qualified symbols, and benchmark-relative outcomes before any strategy or agent score is accepted.', '{"source_repo":"https://github.com/TauricResearch/TradingAgents","license":"Apache-2.0","adoption":"pattern","version_reviewed":"0.2.5","evidence":["tradingagents/dataflows/market_data_validator.py","tradingagents/dataflows/symbol_utils.py","tradingagents/graph/trading_graph.py"]}'::jsonb),
    ('mrchartist_fundamental_coverage', 'Fundamental Coverage Matrix', 'mrchartist', 'fundamental_research', 'research', 'active', 'reference_pattern', 'read_only', ARRAY['fundamental scan','company scorecard','coverage gaps'], ARRAY['company filings','financial statements','price and valuation history'], ARRAY['research.research_papers','portfolio.holding_theses','agent.inbox_items'], ARRAY['postgres_read_model','filing_pdf_extractor'], 'Scanner output is a coverage checklist, not an investment conclusion. Every ratio needs period and source lineage.', 'Build a company coverage matrix across quality, growth, leverage, cash conversion, valuation, governance, and missing evidence; route gaps to the owning analyst.', '{"source_repo":"https://github.com/MrChartist/Funda-Scanner-Base-Project","license":"MIT","adoption":"pattern"}'::jsonb),
    ('mrchartist_options_market_structure', 'Options Market Structure Review', 'mrchartist', 'options_analytics', 'trading', 'active', 'reference_pattern', 'read_only', ARRAY['option chain','oi change','iv surface','straddle'], ARRAY['point-in-time option chain','underlying quote','expiry calendar'], ARRAY['trading.option_chain_snapshots','trading.signals','ops.dashboard_widgets'], ARRAY['postgres_read_model','options_math_engine'], 'OI, IV, Greeks, max pain, and straddle analytics are observations, not executable recommendations.', 'Compute expiry-scoped OI changes, PCR, max pain, IV smile or surface, Greeks, and straddle history with stale-data flags and explicit as-of timestamps.', '{"source_repo":"https://github.com/MrChartist/india-s-best-option-hub","license":"MIT","adoption":"pattern","broker_order_allowed":false}'::jsonb),
    ('mrchartist_flow_regime_monitor', 'Institutional Flow Regime Monitor', 'mrchartist', 'market_flow', 'macro', 'active', 'reference_pattern', 'read_only', ARRAY['fii dii flow','flow regime','flow divergence'], ARRAY['official FII/DII observations','index returns','sector breadth'], ARRAY['market.news_items','strategy.generated_ideas','agent.inbox_items'], ARRAY['postgres_read_model','source_credibility_scorer'], 'Alert on confirmed regime transitions and divergences, not every daily fluctuation.', 'Classify rolling FII and DII flow regimes, detect transition-only alerts, and test whether flow divergence or sector rotation has point-in-time predictive value after costs.', '{"source_repo":"https://github.com/MrChartist/fii-dii-data","license":"MIT","adoption":"pattern"}'::jsonb),
    ('mrchartist_news_curator_reference', 'Newsdesk Curation Reference', 'mrchartist', 'news_curation', 'news', 'active', 'research_reference', 'read_only', ARRAY['curate newsdesk','deduplicate news','sector news'], ARRAY['approved RSS feeds','exchange announcements','portfolio and watchlist symbols'], ARRAY['market.news_items','agent.inbox_items','knowledge.obsidian_notes'], ARRAY['news_feed_reader','source_credibility_scorer'], 'Repository license is not asserted. Do not copy code. Never strip publisher security headers or bypass access controls.', 'Use URL deduplication, source ranking, taxonomy, portfolio relevance, bookmarks, and retention concepts while preserving publisher links and access controls.', '{"source_repo":"https://github.com/MrChartist/Newsdesk","license":"NOASSERTION","adoption":"research_reference_only"}'::jsonb),
    ('mrchartist_tradingview_screener_reference', 'TradingView Screener Reference', 'mrchartist', 'market_screening', 'trading', 'active', 'research_reference', 'read_only', ARRAY['tradingview screener','market movers','indicator lookup'], ARRAY['approved TradingView browser session','stored OHLCV','symbol master'], ARRAY['trading.signals','strategy.generated_ideas','ops.dashboard_widgets'], ARRAY['tradingview_desktop_controller','postgres_read_model'], 'Repository license is not asserted. Do not copy code. TradingView data must respect account, source, freshness, and redistribution boundaries.', 'Adapt only the endpoint vocabulary for overview, indicators, fundamentals, OHLCV, movers, and screeners; store source lineage and never treat a screen as an order.', '{"source_repo":"https://github.com/MrChartist/tradingview-scraper","license":"NOASSERTION","adoption":"research_reference_only","broker_order_allowed":false}'::jsonb),
    ('mrchartist_commodity_landed_price_reference', 'India Commodity Landed Price Reference', 'mrchartist', 'commodity_analytics', 'macro', 'active', 'research_reference', 'read_only', ARRAY['commodity landed price','gold silver conversion','commodity tracker'], ARRAY['international benchmark quote','FX observation','dated duty schedule','unit metadata'], ARRAY['market.price_quotes','research.research_papers','ops.dashboard_widgets'], ARRAY['postgres_read_model','data_quality_gate'], 'Repository metadata does not assert a license despite a README badge. Treat as reference only. Indicative levels and duties must be visibly stale when not verified.', 'Normalize units and currencies, apply dated duties with source lineage, distinguish indicative from live observations, and expose formula inputs for audit.', '{"source_repo":"https://github.com/MrChartist/commodity-price-tracker","license":"UNVERIFIED_README_CLAIM","adoption":"research_reference_only"}'::jsonb)
ON CONFLICT (skill_key) DO UPDATE SET
    skill_name=EXCLUDED.skill_name, skill_family=EXCLUDED.skill_family,
    skill_type=EXCLUDED.skill_type, owner_department=EXCLUDED.owner_department,
    status=EXCLUDED.status, execution_mode=EXCLUDED.execution_mode,
    permission_level=EXCLUDED.permission_level, trigger_phrases=EXCLUDED.trigger_phrases,
    input_sources=EXCLUDED.input_sources, output_targets=EXCLUDED.output_targets,
    required_tools=EXCLUDED.required_tools, risk_notes=EXCLUDED.risk_notes,
    prompt_template=EXCLUDED.prompt_template, config=EXCLUDED.config, updated_at=now();

INSERT INTO agent.workflow_registry (
    workflow_key, workflow_name, workflow_type, owner_agent, trigger_type,
    status, permission_level, input_sources, output_targets,
    approval_required, schedule_hint, notes, metadata
) VALUES
    ('checkpointed_research_committee','Checkpointed Research Committee','research_committee','Research Director','manual_or_agent','active','read_only',ARRAY['research.research_papers','agent.worker_runs','portfolio.holding_theses','market.news_items'],ARRAY['agent.agent_messages','agent.worker_runs','knowledge.obsidian_notes','agent.approvals'],true,'on material thesis, strategy, filing, or operator request','Independent analysis, bounded bull/bear debate, independent risk challenge, typed decision, and resumable state. Human review is required; no order path.','{"source_pattern":"TradingAgents 0.2.5","outcomes":["more_research","abstain","reject","human_review"],"point_in_time":true,"broker_order_allowed":false}'::jsonb),
    ('outcome_grounded_decision_review','Outcome-Grounded Decision Review','post_decision_review','Performance Analyst','scheduled_or_manual','active','read_only',ARRAY['strategy.research_cycles','strategy.performance_snapshots','trading.trade_activity_ledger'],ARRAY['strategy.validation_reviews','knowledge.obsidian_notes','agent.inbox_items'],true,'after horizon expiry or thesis review date','Compare decision process and realized outcome without overwriting history or automatically changing model weights.','{"source_pattern":"TradingAgents 0.2.5","immutable_original":true,"benchmark_required":true,"auto_model_update":false}'::jsonb),
    ('mrchartist_multi_source_intelligence','MrChartist Multi-Source Intelligence Review','source_research','Research Director','manual_or_scheduled','active','read_only',ARRAY['research.research_papers','market.news_items','trading.option_chain_snapshots','trading.ohlcv'],ARRAY['strategy.generated_ideas','agent.worker_runs','knowledge.obsidian_notes'],true,'source refresh then specialist review','Use trusted source concepts for coverage, options, flows, news, screeners, and commodities; source workers must separate live, stale, indicative, and inferred data.','{"source_pattern":"MrChartist reviewed repositories","code_imported":false,"license_gate_required":true,"broker_order_allowed":false}'::jsonb)
ON CONFLICT (workflow_key) DO UPDATE SET
    workflow_name=EXCLUDED.workflow_name, workflow_type=EXCLUDED.workflow_type,
    owner_agent=EXCLUDED.owner_agent, trigger_type=EXCLUDED.trigger_type,
    status=EXCLUDED.status, permission_level=EXCLUDED.permission_level,
    input_sources=EXCLUDED.input_sources, output_targets=EXCLUDED.output_targets,
    approval_required=EXCLUDED.approval_required, schedule_hint=EXCLUDED.schedule_hint,
    notes=EXCLUDED.notes, metadata=EXCLUDED.metadata, updated_at=now();

COMMIT;
